/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CWizDirForm.java
 *
 * Created on 2010-8-19, 12:25:28
 */
package com.bca.utool.cwiz;

import com.bca.utool.cwiz.wa.CWizCanvasForm;
import com.bca.utool.cwiz.wa.CWizCodePreviewForm;

/**
 *
 * @author pxz
 */
public class CWizWorkAreaForm extends javax.swing.JPanel {

    private static CWizWorkAreaForm inst = null;

    /**
     * @return the inst
     */
    public static CWizWorkAreaForm getInst() {
        if (inst == null) {
            inst = new CWizWorkAreaForm();
        }
        return inst;
    }

    /** Creates new form CWizDirForm */
    public CWizWorkAreaForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpane = new javax.swing.JTabbedPane();
        jPanel2 = CWizCanvasForm.getInst();
        jPanel1 = CWizCodePreviewForm.getInst();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        tpane.addTab("Õº–Œ«¯”Ú", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        tpane.addTab("¥˙¬Î‘§¿¿", jPanel1);

        add(tpane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane tpane;
    // End of variables declaration//GEN-END:variables
}
