/*
 * NCanvasForm.java
 *
 * Created on 2008ï¿½ï¿½8ï¿½ï¿½21ï¿½ï¿½, ï¿½ï¿½ï¿½ï¿½6:54
 */
package com.bca.utool.cwiz;

import com.bca.toolkit.top.tools.sql.qb.QbPropForm;
import com.bca.pub.gui.BcaDockingForm;
import com.bca.pub.gui.BcaDockingUnit;
import net.infonode.docking.DockingWindow;
import net.infonode.docking.title.DockingWindowTitleProvider;

/**
 *
 * @author  pxz
 */
public class UtCWizDockForm extends BcaDockingForm implements DockingWindowTitleProvider {

    //Îªï¿½ï¿½ï¿½Úµï¿½ï¿½ï¿½ï¿½Í¬ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä±ï¿½ï¿½â¶¯Ì¬ï¿½Ä±ä£¬ï¿½ï¿½ï¿½Ô°ï¿½BcaDockingUnitï¿½ï¿½ï¿½é¶¨ï¿½ï¿½Îªï¿½ï¿½ï¿½È«ï¿½Ö±ï¿½ï¿½ï¿½ï¿½ï¿½Í¨ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â£ï¿½ï¿½ï¿½Ð©ï¿½ï¿½ï¿½ï¿½Ó¦ï¿½ï¿½ï¿½ï¿½createViews()ï¿½ï¿½ï¿½ï¿½ï¿½Ú¶ï¿½ï¿½å¡£
    private BcaDockingUnit[] leftDockUnit = new BcaDockingUnit[2];
    private BcaDockingUnit[] centerDockUnit = new BcaDockingUnit[1];
    private BcaDockingUnit[] rightDockUnit = new BcaDockingUnit[3];
    private BcaDockingUnit[] bottomDockUnit = new BcaDockingUnit[1];
//    final DynamicViewTitle canvasTitleProvider = new DynamicViewTitle();
    private static UtCWizDockForm inst = null;

    public static UtCWizDockForm getInst() {
        if (inst == null) {
            inst = new UtCWizDockForm();
        }
        return inst;
    }

    /** Creates new form BeanForm */
    private UtCWizDockForm() {
        //initComponents();
        setLayout(new java.awt.BorderLayout());

        super.doCreateDockWindows();
        createViews(); //create views
        super.showViews();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    //Create views
    private void createViews() {
        leftDockUnit[0] = new BcaDockingUnit(CWizDirForm.getInst(), 0.5f, null, "¹¤³§Ä¿Â¼", super.getVIEW_ICON(), false);
        leftDockUnit[1] = new BcaDockingUnit(CWizDbresForm.getInst(), 0.5f, null, "Êý¾Ý×ÊÔ´", super.getVIEW_ICON(), false);

        centerDockUnit[0] = new BcaDockingUnit(CWizWorkAreaForm.getInst(), 0.3f, null, "¹¤×÷ÇøÓò", super.getVIEW_ICON(), false);
//        centerDockUnit[1] = new BcaDockingUnit(FlowWorkSheetTopComponent.findInstance(), 0.7f, null, "ï¿½ï¿½ï¿½Ì»ï¿½ï¿½ï¿½", super.getVIEW_ICON(), false);

        rightDockUnit[0] = new BcaDockingUnit(QbPropForm.getInst(), 0.5f, null, "ÊôÐÔ", super.getVIEW_ICON(), false);
        rightDockUnit[1] = new BcaDockingUnit(CWizMethodForm.getInst(), 0.3f, null, "·½·¨", super.getVIEW_ICON(), false);
        rightDockUnit[2] = new BcaDockingUnit(CWizHelpForm.getInst(), 0.2f, null, "°ïÖú", super.getVIEW_ICON(), false);

        javax.swing.JScrollPane logScrollPane = new javax.swing.JScrollPane();
        logScrollPane.setViewportView(com.bca.log.LogTextPane.getLogTextPane());
        bottomDockUnit[0] = new BcaDockingUnit(logScrollPane, 1f, null, "ÈÕÖ¾", super.getVIEW_ICON(), true);

        super.setHorizontalLayout(0.18f, 0.66f, 0.16f);
        super.setVerticalLayout(0.7f, 0.3f);
        super.loadDockingForms(leftDockUnit, rightDockUnit, bottomDockUnit, centerDockUnit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
//    public RootWindow getRootWindowForShow() {
//        return super.getRootWindow();
//    }
//    public void setCanvasTitle(String title) {
//        canvasTitleProvider.setTitle(title);
////        FlowWorkSheetTopComponent.findInstance().repaint();
////        canvasTitleProvider.notifyAll();
////        views[3].updateUI();
//    }
    String title = "´úÂë¹¤³§";

    public void setTitle(String title) {
        this.title = title;

//             this.repaint();
//        this.updateUI();
//
//        views[3].updateUI();
//        views[3].doLayout();
//        SwingUtilities.updateComponentTreeUI(this);
//        SwingUtilities.updateComponentTreeUI(views[3]);

        centerDockUnit[1].getDockingWindow().getWindowProperties().setTitleProvider(new DockingWindowTitleProvider() {

            @Override
            public String getTitle(DockingWindow window) {
                return "";
            }
        });
        centerDockUnit[1].getDockingWindow().getWindowProperties().setTitleProvider(this);
//        SwingUtilities.updateComponentTreeUI(this);
    }

    @Override
    public String getTitle(DockingWindow window) {
        return title;
    }
}
