/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cf_ShFactoryOptionDialog.java
 *
 * Created on 2012-6-27, 12:07:47
 */
package com.bca.toolkit.top.tools.sql.impl.hkh5;

import com.bca.api.pub.Ret;
import com.bca.pub.tools.Filetool;
import com.bca.pub.tools.Numtool;
import com.bca.toolkit.app.BcaToolkit;
import com.bca.toolkit.top.tools.orm.PojoAttribute;
import com.bca.toolkit.top.tools.sql.I_FactoryOptDlg;
import com.bca.toolkit.top.tools.sql.SrcFactoryBean;
import com.bca.toolkit.top.tools.sql.opt.CodeFactoryOptions;
import java.io.File;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;

/**
 *
 * @author pxz
 */
public class Cf_Hkh5OptionDialog extends javax.swing.JDialog implements I_FactoryOptDlg {

    public Cf_Hkh5OptionDialog() {
        super(BcaToolkit.getApp().getMainFrame(), true);
        initComponents();
        wfinit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        miLocateSrc = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        pkgHomeBox = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pkgTailBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        projHomeDirField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        projNameBox = new javax.swing.JComboBox();
        remCompareBox = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dbupsBox = new javax.swing.JComboBox();
        parenetMenuNameBox = new javax.swing.JComboBox();
        authRoleBox = new javax.swing.JComboBox();
        codeCharsetBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        dosScriptCharsetBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        numberPackBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        busiDBupsBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        pkgRootBox = new javax.swing.JComboBox();

        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        miLocateSrc.setText("定位...");
        miLocateSrc.setName("miLocateSrc"); // NOI18N
        miLocateSrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLocateSrcActionPerformed(evt);
            }
        });
        jPopupMenu1.add(miLocateSrc);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BCA代码工厂--选项(翰科框架)"); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText("pkg home:");
        jLabel1.setName("jLabel1"); // NOI18N

        pkgHomeBox.setEditable(true);
        pkgHomeBox.setName("pkgHomeBox"); // NOI18N
        pkgHomeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkgHomeBoxActionPerformed(evt);
            }
        });

        okButton.setText("确定"); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("取消"); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("pkg tail:");
        jLabel3.setName("jLabel3"); // NOI18N

        pkgTailBox.setEditable(true);
        pkgTailBox.setName("pkgTailBox"); // NOI18N

        jLabel4.setText("目标项目home目录:");
        jLabel4.setName("jLabel4"); // NOI18N

        projHomeDirField.setComponentPopupMenu(jPopupMenu1);
        projHomeDirField.setName("projHomeDirField"); // NOI18N

        jLabel2.setText("项目名称:");
        jLabel2.setName("jLabel2"); // NOI18N

        projNameBox.setEditable(true);
        projNameBox.setName("projNameBox"); // NOI18N
        projNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projNameBoxActionPerformed(evt);
            }
        });

        remCompareBox.setText("rem比对脚本");
        remCompareBox.setName("remCompareBox"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel5.setText("授权db登录(user/pwd@sid):");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("上级菜单名称:");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("授权给角色:");
        jLabel7.setName("jLabel7"); // NOI18N

        dbupsBox.setEditable(true);
        dbupsBox.setName("dbupsBox"); // NOI18N

        parenetMenuNameBox.setEditable(true);
        parenetMenuNameBox.setName("parenetMenuNameBox"); // NOI18N

        authRoleBox.setEditable(true);
        authRoleBox.setName("authRoleBox"); // NOI18N

        codeCharsetBox.setEditable(true);
        codeCharsetBox.setName("codeCharsetBox"); // NOI18N

        jLabel8.setText("代码字符集:");
        jLabel8.setName("jLabel8"); // NOI18N

        dosScriptCharsetBox.setEditable(true);
        dosScriptCharsetBox.setName("dosScriptCharsetBox"); // NOI18N

        jLabel9.setText("dos脚本字符集:");
        jLabel9.setName("jLabel9"); // NOI18N

        numberPackBox.setText("数据类型采用类包装");
        numberPackBox.setName("numberPackBox"); // NOI18N

        jLabel10.setText("业务db登录(user/pwd@sid):");
        jLabel10.setName("jLabel10"); // NOI18N

        busiDBupsBox.setEditable(true);
        busiDBupsBox.setName("busiDBupsBox"); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(Cf_Hkh5OptionDialog.class, "Cf_Hkh5OptionDialog.jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        pkgRootBox.setEditable(true);
        pkgRootBox.setName("pkgRootBox"); // NOI18N
        pkgRootBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkgRootBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberPackBox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projHomeDirField, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(remCompareBox)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(okButton)
                            .addComponent(cancelButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dbupsBox, 0, 277, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parenetMenuNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authRoleBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codeCharsetBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dosScriptCharsetBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(busiDBupsBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pkgRootBox, 0, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pkgHomeBox, 0, 112, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pkgTailBox, 0, 136, Short.MAX_VALUE)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(projHomeDirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pkgRootBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pkgHomeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(pkgTailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(projNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton)
                    .addComponent(remCompareBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numberPackBox)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dbupsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(parenetMenuNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(authRoleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(busiDBupsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(codeCharsetBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosScriptCharsetBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    pkgRoot = (String) pkgRootBox.getSelectedItem();
    pkgHome = (String) pkgHomeBox.getSelectedItem();
    pkgTail = (String) pkgTailBox.getSelectedItem();
    projName = (String) projNameBox.getSelectedItem();

    boolean b0 = opt.regPkgRoot(pkgRoot);
    boolean b1 = opt.regPkgHome(pkgHome);
    boolean b15 = opt.regPkgTail(pkgTail);
    boolean b2 = opt.regprojName(projName);

    dbups = (String) dbupsBox.getSelectedItem();
    parenetMenuName = (String) parenetMenuNameBox.getSelectedItem();
    authRole = (String) authRoleBox.getSelectedItem();
    codeCharset = (String) codeCharsetBox.getSelectedItem();
    dosScriptCharset = (String) dosScriptCharsetBox.getSelectedItem();
    busiDBups = (String) busiDBupsBox.getSelectedItem();

    opt.regMemListName(dbups, "dbups");
    opt.regMemListName(parenetMenuName, "parenetMenuName");
    opt.regMemListName(authRole, "authRole");
    opt.regMemListName(codeCharset, "codeCharset");
    opt.regMemListName(dosScriptCharset, "dosScriptCharset");
    opt.regMemListName(busiDBups, "busiDBups");

    opt.setProperty("projHomeDir", projHomeDirField.getText());
    opt.setProperty("numberPackFlag", Boolean.toString(numberPackBox.isSelected()));
    // if (b1 || b15 || b2) {
    Filetool.saveSerializeFile("status" + File.separator + "CodeFact.cfg", opt);
    //}

    pojoAttr.setProperty("pkgRoot", pkgRoot);
    pojoAttr.setProperty("pkgHome", pkgHome);
    pojoAttr.setProperty("pkgTail", pkgTail);
    pojoAttr.setProperty("projName", projName);
    pojoAttr.setProperty("projHomeDir", projHomeDirField.getText());

    pojoAttr.setProperty("hxhkBatRem", remCompareBox.isSelected() ? "rem" : "");

    pojoAttr.setProperty("dbups", dbups);
    pojoAttr.setProperty("busiDBups", busiDBups);
    pojoAttr.setProperty("parenetMenuName", parenetMenuName);
    pojoAttr.setProperty("authRole", authRole);
    pojoAttr.setProperty("codeCharset", codeCharset);
    pojoAttr.setProperty("dosScriptCharset", dosScriptCharset);
    pojoAttr.setProperty("numberPackFlag", Boolean.toString(numberPackBox.isSelected()));

    setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.setVisible(false);
}//GEN-LAST:event_cancelButtonActionPerformed

private void pkgHomeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkgHomeBoxActionPerformed
//    if (opt == null) {   // 界面尚未打开。
//        return;
//    }
//    String s = (String) this.pkgNameBox.getSelectedItem();
//    if (s == null || s.isEmpty()) {
//        return;
//    }
//    boolean b = opt.regPackage(s);
//    if (b) {
//        Filetool.saveSerializeFile("status" + File.separator + "CodeFact.cfg", opt);
//    }
}//GEN-LAST:event_pkgHomeBoxActionPerformed

private void miLocateSrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLocateSrcActionPerformed
    JFileChooser fc = new JFileChooser(projHomeDirField.getText());
    fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    fc.showSaveDialog(BcaToolkit.getApp().getMainFrame());
    if (fc == null) {
        return;
    }
    File f = fc.getSelectedFile();
    if (f == null) {
        return;
    }
    projHomeDirField.setText(f.getAbsolutePath());
}//GEN-LAST:event_miLocateSrcActionPerformed

private void projNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projNameBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_projNameBoxActionPerformed

    private void pkgRootBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkgRootBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pkgRootBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox authRoleBox;
    private javax.swing.JComboBox busiDBupsBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox codeCharsetBox;
    private javax.swing.JComboBox dbupsBox;
    private javax.swing.JComboBox dosScriptCharsetBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem miLocateSrc;
    private javax.swing.JCheckBox numberPackBox;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox parenetMenuNameBox;
    private javax.swing.JComboBox pkgHomeBox;
    private javax.swing.JComboBox pkgRootBox;
    private javax.swing.JComboBox pkgTailBox;
    private javax.swing.JTextField projHomeDirField;
    private javax.swing.JComboBox projNameBox;
    private javax.swing.JCheckBox remCompareBox;
    // End of variables declaration//GEN-END:variables
//    public String getPkgName() {
//        return pkgHome;
//    }
    String pkgRoot = "";
    String pkgHome = "";
    String pkgTail = "";
    String projName = "";
    String dbups = "";
    String busiDBups = "";
    String parenetMenuName = "";
    String authRole = "";
    String codeCharset = "";
    String dosScriptCharset = "";

//    public void setPkgName(String packageName) {
//    }
    private void setPkgName(String pkgRoot, String pkgHome, String pkgTail) {
        if (pkgRoot != null && !pkgRoot.isEmpty()) {
            this.pkgRoot = pkgRoot;
            this.pkgRootBox.setSelectedItem(pkgRoot);
        }
        if (pkgHome != null && !pkgHome.isEmpty()) {
            this.pkgHome = pkgHome;
            this.pkgHomeBox.setSelectedItem(pkgHome);
        }
        if (pkgTail != null && !pkgTail.isEmpty()) {
            this.pkgTail = pkgTail;
            this.pkgTailBox.setSelectedItem(pkgTail);
        }
    }
    // 
    final Ret ret = new Ret();
    CodeFactoryOptions opt;

    private void wfinit() {
        opt = (CodeFactoryOptions) Filetool.restoreObjFromSerialzeFile("status" + File.separator + "CodeFact.cfg", ret);
        if (opt == null) {
            opt = new CodeFactoryOptions();
        }
        opt.checkFields();

        for (String pkg : opt.recentUsedProjNames) {
            if (pkg != null && !pkg.isEmpty()) {
                this.projNameBox.addItem(pkg);
            }
        }
        if (opt.recentUsedProjNames.isEmpty()) {
            projNameBox.addItem("");
        }
        for (String pkg : opt.recentUsedPackageRoot) {
            if (pkg != null && !pkg.isEmpty()) {
                this.pkgRootBox.addItem(pkg);
            }
        }
        if (opt.recentUsedPackageRoot.isEmpty()) {
            pkgRootBox.addItem("");
        }
        for (String pkg : opt.recentUsedPackageHome) {
            if (pkg != null && !pkg.isEmpty()) {
                this.pkgHomeBox.addItem(pkg);
            }
        }
        if (opt.recentUsedPackageHome.isEmpty()) {
            pkgHomeBox.addItem("");
        }
        for (String pkg : opt.recentUsedPackageTail) {
            if (pkg != null && !pkg.isEmpty()) {
                this.pkgTailBox.addItem(pkg);
            }
        }
        if (opt.recentUsedPackageTail.isEmpty()) {
            pkgTailBox.addItem("");
        }
        projNameBox.setSelectedIndex(0);
        pkgHomeBox.setSelectedIndex(0);
        pkgTailBox.setSelectedIndex(0);
//        projNameBox.setSelectedIndex(0);

        loadOptText(this.dbupsBox, "dbups");
        loadOptText(busiDBupsBox, "busiDBups");
        loadOptText(this.parenetMenuNameBox, "parenetMenuName");
        loadOptText(this.authRoleBox, "authRole");
        loadOptText(this.codeCharsetBox, "codeCharset");
        loadOptText(this.dosScriptCharsetBox, "dosScriptCharset");

        this.projHomeDirField.setText(opt.getProperty("projHomeDir"));
        this.numberPackBox.setSelected(Numtool.parseBoolean(opt.getProperty("numberPackFlag")));
    }

    /**
     * @return the projName
     */
    public String getprojName() {
        return projName;
    }

    /**
     * @param projName the projName to set
     */
    public void setprojName(String projName) {
        if (projName != null && !projName.isEmpty()) {
            this.projName = projName;
            this.projNameBox.setSelectedItem(projName);
        }
    }
    PojoAttribute pojoAttr;

    @Override
    public void loadOptions(SrcFactoryBean f) {
        this.pojoAttr = f.pojoAttr;
        String s = f.pojoAttr.getProperty("projHomeDir");
        if (!s.isEmpty()) {
            projHomeDirField.setText(s);
        }
        setPkgName(f.pojoAttr.getProperty("pkgRoot"), f.pojoAttr.getProperty("pkgHome"), f.pojoAttr.getProperty("pkgTail"));
        setprojName(f.pojoAttr.getProperty("projName"));

        // numberPackBox.setSelected(Numtool.parseBoolean(pojoAttr.getProperty("numberPackFlag")));
    }

    @Override
    public PojoAttribute getPojoAttribute() {
        return pojoAttr;
    }

    private void loadOptText(JComboBox box, String grp) {
        List<String> list = this.opt.getMemList(grp);
        for (String s : list) {
            box.addItem(s);
        }
        if (list.isEmpty()) {
            box.addItem("");
        }
        box.setSelectedIndex(0);
    }

    @Override
    public void setProjectInfo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
