/*
 * NStudioFrame2.java
 *
 * Created on 2008年10月15日, 下午4:04
 */
package com.bca.toolkit;

import com.bca.pub.tools.Nettool;
import com.bca.pub.tools.ProgressbarWindow;
import com.bca.pub.tools.Wftool;
import com.bca.studio.menu.I_DynBcaMenuBar;

import com.bca.toolkit.top.NTemplateForm;
import com.bca.studio.top.help.AboutBcaDialog;
import com.bca.toolkit.top.tools.BcaToolsTopComponent;
import com.bca.toolkit.app.BcaToolkit;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JMenu;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import org.openide.util.Exceptions;

/**
 *
 * @author  BCA INC
 */
public class BcaToolkitFrame extends javax.swing.JFrame {

    final BcaToolkit app;

    /** Creates new form NStudioFrame2 */
    public BcaToolkitFrame(final BcaToolkit app) {
        this.app = app;
        initComponents();
        // wfinit();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);   // 配合重载的 processWindowEvent 函数。
         //以下代码改变界面的观感或者叫风格
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        } 
    }

    @Override
    protected void processWindowEvent(WindowEvent e) {
        super.processWindowEvent(e);
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            miExitActionPerformed(null);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cardPanel = new javax.swing.JPanel();
        templatePanel = new javax.swing.JPanel();
        toolsPanel = new javax.swing.JPanel();
        statusField = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        miConfigManager = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        menuWin = new javax.swing.JMenu();
        miTemplateManager = new javax.swing.JRadioButtonMenuItem();
        miBcaTools = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miHelpCenter = new javax.swing.JMenuItem();
        miAboutBCA = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cardPanel.setLayout(new java.awt.CardLayout());

        templatePanel.setLayout(new java.awt.BorderLayout());
        cardPanel.add(templatePanel, "templatePanel");

        toolsPanel.setLayout(new java.awt.BorderLayout());
        cardPanel.add(toolsPanel, "toolsPanel");

        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        statusField.setEditable(false);
        getContentPane().add(statusField, java.awt.BorderLayout.SOUTH);

        menuFile.setText("系统"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/bca/toolkit/Bundle"); // NOI18N
        miConfigManager.setText(bundle.getString("BcaToolkitFrame.miConfigManager.text")); // NOI18N
        miConfigManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConfigManagerActionPerformed(evt);
            }
        });
        menuFile.add(miConfigManager);

        miExit.setText("退出"); // NOI18N
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        menuFile.add(miExit);

        menuBar.add(menuFile);

        menuWin.setText("工作视图"); // NOI18N

        buttonGroup1.add(miTemplateManager);
        miTemplateManager.setText("模板管理器"); // NOI18N
        miTemplateManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTemplateManagerActionPerformed(evt);
            }
        });
        menuWin.add(miTemplateManager);

        buttonGroup1.add(miBcaTools);
        miBcaTools.setSelected(true);
        miBcaTools.setText(bundle.getString("BcaToolkitFrame.miBcaTools.text")); // NOI18N
        miBcaTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBcaToolsActionPerformed(evt);
            }
        });
        menuWin.add(miBcaTools);

        menuBar.add(menuWin);

        jMenu1.setText(bundle.getString("BcaToolkitFrame.jMenu1.text")); // NOI18N

        miHelpCenter.setText(bundle.getString("BcaToolkitFrame.miHelpCenter.text")); // NOI18N
        jMenu1.add(miHelpCenter);

        miAboutBCA.setText(bundle.getString("BcaToolkitFrame.miAboutBCA.text")); // NOI18N
        miAboutBCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutBCAActionPerformed(evt);
            }
        });
        jMenu1.add(miAboutBCA);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
    boolean b = Wftool.confirmDialog("退出提示", "真的要退出BCA-Toolkit？\n请注意保存好模型，以免丢失数据。");
    if (b) {
        BcaToolkit.getApp().shutdownApp();
    }
}//GEN-LAST:event_miExitActionPerformed

private void miTemplateManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTemplateManagerActionPerformed
    showCard("templatePanel");
}//GEN-LAST:event_miTemplateManagerActionPerformed

private void miBcaToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBcaToolsActionPerformed
    showCard("toolsPanel");
}//GEN-LAST:event_miBcaToolsActionPerformed

private void miConfigManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConfigManagerActionPerformed
    com.bca.studio.act.tools.StudioConfigForm cp = new com.bca.studio.act.tools.StudioConfigForm();
    cp.work();
}//GEN-LAST:event_miConfigManagerActionPerformed

private void miAboutBCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutBCAActionPerformed
    AboutBcaDialog dlg = new AboutBcaDialog(this, true);
    dlg.setBounds(app.getCenterBounds(dlg.getPreferredSize()));
    dlg.setVisible(true);
}//GEN-LAST:event_miAboutBCAActionPerformed

    public void setStatus(String s) {
        this.statusField.setText(s);
    }
    I_DynBcaMenuBar activeDMenuBar = null;

    public void showCard(String cardName) {
        java.awt.CardLayout l = (java.awt.CardLayout) cardPanel.getLayout();
        l.show(cardPanel, cardName);

        if (activeDMenuBar != null) {
            for (JMenu m : activeDMenuBar.getDynMenus()) {
                menuBar.remove(m);
            }
        }

        I_DynBcaMenuBar dmenuBar = dynMenus.get(cardName);
        if (dmenuBar != null) {
            int i = 1;
            for (JMenu m : dmenuBar.getDynMenus()) {
                menuBar.add(m, i++);
            }
        }
        activeDMenuBar = dmenuBar;
    }
// End of variables declaration
    final Map<String, I_DynBcaMenuBar> dynMenus = new HashMap<String, I_DynBcaMenuBar>();

    public void wfinit(ProgressbarWindow bar) {
        Nettool.initSocketFactory();
//        // Timetool.logSysTime(Toolfunc.getCurrentFunctionName());
//        flowCanvasPanel.add(NCanvasForm.getInst(), java.awt.BorderLayout.CENTER);
//        dynMenus.put("flowCanvasPanel", new NCanvasMenuBar());
//        showCard("flowCanvasPanel");
//
//        bar.incValue();
//
//        // Timetool.logSysTime(Toolfunc.getCurrentFunctionName());
//        debugPanel.add(new NDebugForm().getRootWindow(), java.awt.BorderLayout.CENTER);
//        // showCard("debugPanel");
//
//        // Timetool.logSysTime(Toolfunc.getCurrentFunctionName());
//        managerPanel.add(new NManagerForm().getRootWindow(), java.awt.BorderLayout.CENTER);
//		// showCard("managerPanel");
//
        // Timetool.logSysTime(Toolfunc.getCurrentFunctionName());
        templatePanel.add(new NTemplateForm().getRootWindow(), java.awt.BorderLayout.CENTER);
//		// showCard("templatePanel");
//
//        // Timetool.logSysTime(Toolfunc.getCurrentFunctionName());
//        blogPanel.add(new NBlogForm().getRootWindow(), java.awt.BorderLayout.CENTER);
        // showCard("blogPanel");

        // Timetool.logSysTime(Toolfunc.getCurrentFunctionName());
        getToolsPanel().add(BcaToolsTopComponent.getInst(), java.awt.BorderLayout.CENTER);

        bar.incValue();
//        // Timetool.logSysTime(Toolfunc.getCurrentFunctionName());
//        if (BStudioFcSwitch.codeFatory) {
        showCard("toolsPanel");
//        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuWin;
    private javax.swing.JMenuItem miAboutBCA;
    private javax.swing.JRadioButtonMenuItem miBcaTools;
    private javax.swing.JMenuItem miConfigManager;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miHelpCenter;
    private javax.swing.JRadioButtonMenuItem miTemplateManager;
    private javax.swing.JTextField statusField;
    private javax.swing.JPanel templatePanel;
    private javax.swing.JPanel toolsPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the toolsPanel
     */
    public javax.swing.JPanel getToolsPanel() {
        return toolsPanel;
    }

    /**
     * @param toolsPanel the toolsPanel to set
     */
    public void setToolsPanel(javax.swing.JPanel toolsPanel) {
        this.toolsPanel = toolsPanel;
    }
}
