package com.bca.toolkit.top.tools.sql.impl.util.w.jt;

import com.bca.toolkit.top.tools.sql.impl.util.w.WebUiTemplUnit;
import com.bca.pub.gui.jtablex.I_JTableDataHandler;
import com.bca.pub.gui.jtablex.I_TableRowGuiBinder;
import com.bca.pub.tools.Numtool;
import java.awt.event.ActionEvent;
import javax.swing.JMenuItem;
import javax.swing.text.BadLocationException;
import javax.swing.text.JTextComponent;

/**
 * WEB_UI_TEMPL_UNIT管理：详细编辑form
 *
 * @author 北京华夏翰科科技有限公司 http://www.hxhk.com.cn 2013-04-09 14:25:40.453
 */
public class WebUiTemplUnitRowEditorForm extends javax.swing.JPanel implements I_TableRowGuiBinder<WebUiTemplUnit> {

    final WebUiTemplUnitJTableForm parentForm;

    WebUiTemplUnitRowEditorForm(WebUiTemplUnitJTableForm aThis) {
        this.parentForm = aThis;
        initComponents();
        wfinit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popArgName = new javax.swing.JPopupMenu();
        estyleArgNameLabel = new javax.swing.JLabel();
        estyleArgNameField = new javax.swing.JTextField();
        estyleContentLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        estyleContentField = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        scopeBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        idxField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        noteField = new javax.swing.JTextField();

        popArgName.setName("popArgName"); // NOI18N

        setName("Form"); // NOI18N

        estyleArgNameLabel.setText(org.openide.util.NbBundle.getMessage(WebUiTemplUnitRowEditorForm.class, "WebUiTemplUnitRowEditorForm.estyleArgNameLabel.text")); // NOI18N
        estyleArgNameLabel.setName("estyleArgNameLabel"); // NOI18N

        estyleArgNameField.setEditable(false);
        estyleArgNameField.setComponentPopupMenu(popArgName);
        estyleArgNameField.setName("estyleArgNameField"); // NOI18N

        estyleContentLabel.setText(org.openide.util.NbBundle.getMessage(WebUiTemplUnitRowEditorForm.class, "WebUiTemplUnitRowEditorForm.estyleContentLabel.text")); // NOI18N
        estyleContentLabel.setName("estyleContentLabel"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("取消");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        estyleContentField.setComponentPopupMenu(popArgName);
        estyleContentField.setName("estyleContentField"); // NOI18N
        jScrollPane1.setViewportView(estyleContentField);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(WebUiTemplUnitRowEditorForm.class, "WebUiTemplUnitRowEditorForm.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        scopeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "f", "t" }));
        scopeBox.setName("scopeBox"); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(WebUiTemplUnitRowEditorForm.class, "WebUiTemplUnitRowEditorForm.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        idxField.setText(org.openide.util.NbBundle.getMessage(WebUiTemplUnitRowEditorForm.class, "WebUiTemplUnitRowEditorForm.idxField.text")); // NOI18N
        idxField.setName("idxField"); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(WebUiTemplUnitRowEditorForm.class, "WebUiTemplUnitRowEditorForm.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        noteField.setText(org.openide.util.NbBundle.getMessage(WebUiTemplUnitRowEditorForm.class, "WebUiTemplUnitRowEditorForm.noteField.text")); // NOI18N
        noteField.setName("noteField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estyleArgNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(estyleArgNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scopeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idxField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estyleContentLabel)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(noteField))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelButton)
                            .addComponent(okButton)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(estyleArgNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(scopeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(idxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(estyleArgNameLabel))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estyleContentLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(okButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    if (h != null && bindingBean != null) {
        this.updateBean();
        this.h.fillRow(this.bindingRow, this.bindingBean);
        parentForm.savePool();
    }
}//GEN-LAST:event_okButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.rebind(bindingRow, bindingBean);
}//GEN-LAST:event_cancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField estyleArgNameField;
    private javax.swing.JLabel estyleArgNameLabel;
    private javax.swing.JTextPane estyleContentField;
    private javax.swing.JLabel estyleContentLabel;
    private javax.swing.JTextField idxField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField noteField;
    private javax.swing.JButton okButton;
    private javax.swing.JPopupMenu popArgName;
    private javax.swing.JComboBox scopeBox;
    // End of variables declaration//GEN-END:variables
    int bindingRow = 0;
    WebUiTemplUnit bindingBean = null;
    I_JTableDataHandler h;

    @Override
    public void rebind(int rowNo, WebUiTemplUnit e) {
        this.bindingBean = e;
        this.bindingRow = rowNo;

        estyleArgNameField.setText(e == null || e.getEstyleArgName() == null ? "" : e.getEstyleArgName());
        estyleContentField.setText(e == null || e.getEstyleContent() == null ? "" : e.getEstyleContent());
        this.scopeBox.setSelectedItem(Character.toString(e.getScope()));
        this.idxField.setText(Integer.toString(e.getIdx()));
        this.noteField.setText(e.getNote());
    }

    @Override
    public int getBindingRow() {
        return bindingRow;
    }

    @Override
    public WebUiTemplUnit getBindingBean() {
        return bindingBean;
    }

    @Override
    public void setTableDataHandler(I_JTableDataHandler h) {
        this.h = h;
    }

    @Override
    public WebUiTemplUnit updateBean() {
        // 从界面取对象....      
        if (bindingBean == null) {
            return null;
        }
        bindingBean.setEstyleArgName(estyleArgNameField.getText());
        bindingBean.setEstyleContent(estyleContentField.getText());
        bindingBean.setScope(scopeBox.getSelectedItem().toString().charAt(0));
        bindingBean.setIdx(Numtool.parseInt(this.idxField.getText(), 0));
        bindingBean.setNote(noteField.getText());

        return this.bindingBean;
    }

    @Override
    public boolean isSaveEnable() {
        return true;
    }

    @Override
    public void setPkFieldsEditable(boolean b) {
        estyleArgNameField.setEditable(b);

    }

    private void wfinit() {
        createArgNameItem("jspEditStyleUnit");
        createArgNameItem("estyleOnAction");
        createArgNameItem("estyleOnBusi");
        createArgNameItem("estyleOnDao");
        createArgNameItem("estyleOnSql");
        popArgName.addSeparator();

        createArgNameItem("tableName");
        createArgNameItem("entityLable");
        createArgNameItem("fieldName");
        createArgNameItem("fieldLabel");
        createArgNameItem("jdbcType");
        createArgNameItem("mainName");
        createArgNameItem("objVarName");
        createArgNameItem("pkgTail_dir_unix");
        createArgNameItem("varName");
        createArgNameItem("varnameCap");
        createArgNameItem("verifyCol");
    }

    private void onArgNameSelected(JMenuItem miArgName, ActionEvent evt) {
        javax.swing.JMenuItem mi = (javax.swing.JMenuItem) evt.getSource();
        JTextComponent c = (JTextComponent) popArgName.getInvoker();
        try {
            if (estyleArgNameField.equals(c)) {
                if (!estyleArgNameField.isEditable()) {
                    return;
                }
                c.setText(miArgName.getName());
            } else {
                c.getDocument().insertString(c.getCaretPosition(), miArgName.getText(), null);
            }
        } catch (BadLocationException ex) {
            ex.printStackTrace();
        }
    }

    private void createArgNameItem(String argName) {
        final javax.swing.JMenuItem miArgName = new javax.swing.JMenuItem();
        miArgName.setText("${" + argName + "}");
        miArgName.setName(argName);
        popArgName.add(miArgName);
        miArgName.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onArgNameSelected(miArgName, evt);
            }
        });
    }
}
