/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QbTablePopDialog.java
 *
 * Created on 2010-11-8, 23:00:43
 */
package com.bca.toolkit.top.tools.sql.impl.dbwiz;

import com.bca.db.meta.I_WfColumn;
import com.bca.templ.pub.AbstractApp;
import com.bca.toolkit.top.tools.sql.SqlCreateModel;
import com.bca.toolkit.top.tools.sql.qb.QbJTable;
import com.bca.toolkit.top.tools.sql.qb.I_ColBatchDlg;

/**
 *
 * @author pxz
 */
public class QbTablePopDialog_Dbwiz extends javax.swing.JDialog implements I_ColBatchDlg {

    private QbJTable qbJTable;

    /**
     * Creates new form QbTablePopDialog
     */
    public QbTablePopDialog_Dbwiz() {
        super(AbstractApp.getMainFrameOnPossible(), false);
//        this.qbJTable = qbJTable;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        openAllFieldsButton = new javax.swing.JButton();
        criteriaOpen = new javax.swing.JButton();
        criteriaMask = new javax.swing.JButton();
        insertOpen = new javax.swing.JButton();
        insertMask = new javax.swing.JButton();
        addOpen = new javax.swing.JButton();
        addMask = new javax.swing.JButton();
        updateOpen = new javax.swing.JButton();
        updateMask = new javax.swing.JButton();
        selectOpen = new javax.swing.JButton();
        selectMask = new javax.swing.JButton();
        expOpen = new javax.swing.JButton();
        expMask = new javax.swing.JButton();
        impMask = new javax.swing.JButton();
        impOpen = new javax.swing.JButton();
        verifyOpenButton = new javax.swing.JButton();
        verifyCloseButton = new javax.swing.JButton();
        viewBindOpenButton = new javax.swing.JButton();
        viewBindCloseButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        groupButton = new javax.swing.JButton();
        cancelGroupButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        orderButton = new javax.swing.JButton();
        cancelOrderButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        setAsPkButton = new javax.swing.JButton();
        maskPkButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bindingSeqButton = new javax.swing.JButton();
        unbindingSeqButton = new javax.swing.JButton();
        delEStyleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("列批量操作"); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("字段使能开关"));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("jsp:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("导入导出:");
        jLabel2.setName("jLabel2"); // NOI18N

        openAllFieldsButton.setText("打开所有");
        openAllFieldsButton.setName("openAllFieldsButton"); // NOI18N
        openAllFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAllFieldsButtonActionPerformed(evt);
            }
        });

        criteriaOpen.setText(org.openide.util.NbBundle.getMessage(QbTablePopDialog_Dbwiz.class, "QbTablePopDialog_Dbwiz.criteriaOpen.text")); // NOI18N
        criteriaOpen.setName("criteriaOpen"); // NOI18N
        criteriaOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criteriaOpenActionPerformed(evt);
            }
        });

        criteriaMask.setText(org.openide.util.NbBundle.getMessage(QbTablePopDialog_Dbwiz.class, "QbTablePopDialog_Dbwiz.criteriaMask.text")); // NOI18N
        criteriaMask.setName("criteriaMask"); // NOI18N
        criteriaMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criteriaMaskActionPerformed(evt);
            }
        });

        insertOpen.setText(org.openide.util.NbBundle.getMessage(QbTablePopDialog_Dbwiz.class, "QbTablePopDialog_Dbwiz.insertOpen.text")); // NOI18N
        insertOpen.setName("insertOpen"); // NOI18N
        insertOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertOpenActionPerformed(evt);
            }
        });

        insertMask.setText(org.openide.util.NbBundle.getMessage(QbTablePopDialog_Dbwiz.class, "QbTablePopDialog_Dbwiz.insertMask.text")); // NOI18N
        insertMask.setName("insertMask"); // NOI18N
        insertMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertMaskActionPerformed(evt);
            }
        });

        addOpen.setText("add-开");
        addOpen.setName("addOpen"); // NOI18N
        addOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOpenActionPerformed(evt);
            }
        });

        addMask.setText("add-关");
        addMask.setName("addMask"); // NOI18N
        addMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaskActionPerformed(evt);
            }
        });

        updateOpen.setText("update-开");
        updateOpen.setName("updateOpen"); // NOI18N
        updateOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOpenActionPerformed(evt);
            }
        });

        updateMask.setText("update-关");
        updateMask.setName("updateMask"); // NOI18N
        updateMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMaskActionPerformed(evt);
            }
        });

        selectOpen.setText(org.openide.util.NbBundle.getMessage(QbTablePopDialog_Dbwiz.class, "QbTablePopDialog_Dbwiz.selectOpen.text")); // NOI18N
        selectOpen.setName("selectOpen"); // NOI18N
        selectOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectOpenActionPerformed(evt);
            }
        });

        selectMask.setText(org.openide.util.NbBundle.getMessage(QbTablePopDialog_Dbwiz.class, "QbTablePopDialog_Dbwiz.selectMask.text")); // NOI18N
        selectMask.setActionCommand(org.openide.util.NbBundle.getMessage(QbTablePopDialog_Dbwiz.class, "QbTablePopDialog_Dbwiz.selectMask.actionCommand")); // NOI18N
        selectMask.setName("selectMask"); // NOI18N
        selectMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMaskActionPerformed(evt);
            }
        });

        expOpen.setText("导出-开");
        expOpen.setName("expOpen"); // NOI18N
        expOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expOpenActionPerformed(evt);
            }
        });

        expMask.setText("导出-关");
        expMask.setName("expMask"); // NOI18N
        expMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expMaskActionPerformed(evt);
            }
        });

        impMask.setText("导入-关");
        impMask.setName("impMask"); // NOI18N
        impMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impMaskActionPerformed(evt);
            }
        });

        impOpen.setText("导入-开");
        impOpen.setName("impOpen"); // NOI18N
        impOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impOpenActionPerformed(evt);
            }
        });

        verifyOpenButton.setText("验证-开");
        verifyOpenButton.setName("verifyOpenButton"); // NOI18N
        verifyOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyOpenButtonActionPerformed(evt);
            }
        });

        verifyCloseButton.setText("验证-关");
        verifyCloseButton.setName("verifyCloseButton"); // NOI18N
        verifyCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyCloseButtonActionPerformed(evt);
            }
        });

        viewBindOpenButton.setText("view绑定-开");
        viewBindOpenButton.setName("viewBindOpenButton"); // NOI18N
        viewBindOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBindOpenButtonActionPerformed(evt);
            }
        });

        viewBindCloseButton.setText("view绑定-关");
        viewBindCloseButton.setName("viewBindCloseButton"); // NOI18N
        viewBindCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBindCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(verifyOpenButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(viewBindOpenButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(criteriaOpen)
                                            .addComponent(criteriaMask))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selectMask)
                                            .addComponent(selectOpen))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(insertOpen)
                                            .addComponent(insertMask))))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(addMask)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(updateMask))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(addOpen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(updateOpen))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(verifyCloseButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(viewBindCloseButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(expMask)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(impOpen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(impMask)))
                        .addGap(93, 93, 93))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openAllFieldsButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(updateOpen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addOpen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(insertOpen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(criteriaOpen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(criteriaMask)
                            .addComponent(insertMask)
                            .addComponent(addMask)
                            .addComponent(updateMask)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selectOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectMask)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyOpenButton)
                    .addComponent(viewBindOpenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyCloseButton)
                    .addComponent(viewBindCloseButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(openAllFieldsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(expOpen)
                            .addComponent(expMask)
                            .addComponent(impOpen)
                            .addComponent(impMask))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("group by"));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        groupButton.setText("分组字段"); // NOI18N
        buttonGroup2.add(groupButton);
        groupButton.setEnabled(false);
        groupButton.setName("groupButton"); // NOI18N
        groupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButtonActionPerformed(evt);
            }
        });
        jPanel2.add(groupButton);

        cancelGroupButton.setText("取消分组"); // NOI18N
        buttonGroup2.add(cancelGroupButton);
        cancelGroupButton.setEnabled(false);
        cancelGroupButton.setName("cancelGroupButton"); // NOI18N
        cancelGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelGroupButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelGroupButton);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("order By"));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        orderButton.setText("排序字段"); // NOI18N
        buttonGroup3.add(orderButton);
        orderButton.setEnabled(false);
        orderButton.setName("orderButton"); // NOI18N
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });
        jPanel3.add(orderButton);

        cancelOrderButton.setText("取消排序"); // NOI18N
        buttonGroup3.add(cancelOrderButton);
        cancelOrderButton.setEnabled(false);
        cancelOrderButton.setName("cancelOrderButton"); // NOI18N
        cancelOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelOrderButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cancelOrderButton);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("虚拟主键属性设置"));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        setAsPkButton.setText("设为主键");
        setAsPkButton.setName("setAsPkButton"); // NOI18N
        setAsPkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAsPkButtonActionPerformed(evt);
            }
        });
        jPanel4.add(setAsPkButton);

        maskPkButton.setText("关闭主键");
        maskPkButton.setName("maskPkButton"); // NOI18N
        maskPkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maskPkButtonActionPerformed(evt);
            }
        });
        jPanel4.add(maskPkButton);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("SEQ绑定"));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        bindingSeqButton.setText("绑定表SEQ");
        bindingSeqButton.setName("bindingSeqButton"); // NOI18N
        bindingSeqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bindingSeqButtonActionPerformed(evt);
            }
        });
        jPanel5.add(bindingSeqButton);

        unbindingSeqButton.setText("解除SEQ绑定");
        unbindingSeqButton.setName("unbindingSeqButton"); // NOI18N
        unbindingSeqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unbindingSeqButtonActionPerformed(evt);
            }
        });
        jPanel5.add(unbindingSeqButton);

        delEStyleButton.setText("删除编辑风格");
        delEStyleButton.setName("delEStyleButton"); // NOI18N
        delEStyleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delEStyleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delEStyleButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(delEStyleButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        getQbJTable().onPopDialogClosed();
    }//GEN-LAST:event_formWindowClosed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        getQbJTable().orderbySelectedFields(true);
    }//GEN-LAST:event_orderButtonActionPerformed

    private void cancelOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelOrderButtonActionPerformed
        getQbJTable().orderbySelectedFields(false);
    }//GEN-LAST:event_cancelOrderButtonActionPerformed

    private void groupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButtonActionPerformed
        getQbJTable().groupbySelectedFields(true);
    }//GEN-LAST:event_groupButtonActionPerformed

    private void cancelGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelGroupButtonActionPerformed
        getQbJTable().groupbySelectedFields(false);
    }//GEN-LAST:event_cancelGroupButtonActionPerformed

private void openAllFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAllFieldsButtonActionPerformed
    SqlCreateModel sm = qbJTable.getScene().getModel().getSqlModel();
    sm.removeAllFieldMasks();
    updateJTableUI();
}//GEN-LAST:event_openAllFieldsButtonActionPerformed

private void criteriaOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criteriaOpenActionPerformed
    setSelectedFieldsSW("criteria", true);
}//GEN-LAST:event_criteriaOpenActionPerformed

private void criteriaMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criteriaMaskActionPerformed
    setSelectedFieldsSW("criteria", false);
}//GEN-LAST:event_criteriaMaskActionPerformed

private void insertOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertOpenActionPerformed
    setSelectedFieldsSW("listdev", true);
}//GEN-LAST:event_insertOpenActionPerformed

private void insertMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertMaskActionPerformed
    setSelectedFieldsSW("listdev", false);
}//GEN-LAST:event_insertMaskActionPerformed

private void addOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOpenActionPerformed
    setSelectedFieldsSW("add", true);
}//GEN-LAST:event_addOpenActionPerformed

private void addMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaskActionPerformed
    setSelectedFieldsSW("add", false);
}//GEN-LAST:event_addMaskActionPerformed

private void updateOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOpenActionPerformed
    setSelectedFieldsSW("update", true);
}//GEN-LAST:event_updateOpenActionPerformed

private void updateMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMaskActionPerformed
    setSelectedFieldsSW("update", false);
}//GEN-LAST:event_updateMaskActionPerformed

private void selectOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectOpenActionPerformed
    setSelectedFieldsSW("select", true);
}//GEN-LAST:event_selectOpenActionPerformed

private void selectMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMaskActionPerformed
    setSelectedFieldsSW("select", false);
}//GEN-LAST:event_selectMaskActionPerformed

private void expOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expOpenActionPerformed
    setSelectedFieldsSW("exp", true);
}//GEN-LAST:event_expOpenActionPerformed

private void expMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expMaskActionPerformed
    setSelectedFieldsSW("exp", false);
}//GEN-LAST:event_expMaskActionPerformed

private void impOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impOpenActionPerformed
    setSelectedFieldsSW("imp", true);
}//GEN-LAST:event_impOpenActionPerformed

private void impMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impMaskActionPerformed
    setSelectedFieldsSW("imp", false);
}//GEN-LAST:event_impMaskActionPerformed

private void setAsPkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAsPkButtonActionPerformed
    setSelectedFieldsPK(true);
}//GEN-LAST:event_setAsPkButtonActionPerformed

private void maskPkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maskPkButtonActionPerformed
    setSelectedFieldsPK(false);
}//GEN-LAST:event_maskPkButtonActionPerformed

private void verifyOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyOpenButtonActionPerformed
    setSelectedFieldsSW("verify", true);
}//GEN-LAST:event_verifyOpenButtonActionPerformed

private void verifyCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyCloseButtonActionPerformed
    setSelectedFieldsSW("verify", false);
}//GEN-LAST:event_verifyCloseButtonActionPerformed

private void viewBindOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBindOpenButtonActionPerformed
    setSelectedFieldsSW("viewBindingCol", true);
}//GEN-LAST:event_viewBindOpenButtonActionPerformed

private void viewBindCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBindCloseButtonActionPerformed
    setSelectedFieldsSW("viewBindingCol", false);
}//GEN-LAST:event_viewBindCloseButtonActionPerformed

private void bindingSeqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bindingSeqButtonActionPerformed
    setSelectedFieldsSW("bindingSeqCol", true);
}//GEN-LAST:event_bindingSeqButtonActionPerformed

private void unbindingSeqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unbindingSeqButtonActionPerformed
    setSelectedFieldsSW("bindingSeqCol", false);
}//GEN-LAST:event_unbindingSeqButtonActionPerformed

    private void delEStyleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delEStyleButtonActionPerformed
        SqlCreateModel sm = qbJTable.getScene().getModel().getSqlModel();
        for (int row : qbJTable.getSelectedRows()) {
            I_WfColumn col = (I_WfColumn) qbJTable.getModel().getValueAt(row, 0);
            if (col != null) {
                sm.removeUiStyle(col.getSqlName());
            }
        }
        qbJTable.refreshSqlPreview(true);
        updateJTableUI();
    }//GEN-LAST:event_delEStyleButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMask;
    private javax.swing.JButton addOpen;
    private javax.swing.JButton bindingSeqButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cancelGroupButton;
    private javax.swing.JButton cancelOrderButton;
    private javax.swing.JButton criteriaMask;
    private javax.swing.JButton criteriaOpen;
    private javax.swing.JButton delEStyleButton;
    private javax.swing.JButton expMask;
    private javax.swing.JButton expOpen;
    private javax.swing.JButton groupButton;
    private javax.swing.JButton impMask;
    private javax.swing.JButton impOpen;
    private javax.swing.JButton insertMask;
    private javax.swing.JButton insertOpen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton maskPkButton;
    private javax.swing.JButton openAllFieldsButton;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton selectMask;
    private javax.swing.JButton selectOpen;
    private javax.swing.JButton setAsPkButton;
    private javax.swing.JButton unbindingSeqButton;
    private javax.swing.JButton updateMask;
    private javax.swing.JButton updateOpen;
    private javax.swing.JButton verifyCloseButton;
    private javax.swing.JButton verifyOpenButton;
    private javax.swing.JButton viewBindCloseButton;
    private javax.swing.JButton viewBindOpenButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the qbJTable
     */
    public QbJTable getQbJTable() {
        return qbJTable;
    }

    /**
     * @param qbJTable the qbJTable to set
     */
    public void setQbJTable(QbJTable qbJTable) {
        this.qbJTable = qbJTable;
    }

    @Override
    public void wfinit(QbJTable jtable) {
        this.qbJTable = jtable;
        this.setTitle(String.format("表<%s>:列批量动作 (翰科框架)", qbJTable.getModel().getTbean().getTableDetail().getName()));
    }

    private void updateJTableUI() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                qbJTable.updateUI();
            }
        });
    }

    private void setSelectedFieldsSW(String grp, boolean sw) {
        SqlCreateModel sm = qbJTable.getScene().getModel().getSqlModel();
        for (int row : qbJTable.getSelectedRows()) {
            I_WfColumn col = (I_WfColumn) qbJTable.getModel().getValueAt(row, 0);
            if (col != null) {
                if (sw) {
                    sm.removeFieldMask(grp, col.getSqlName());
                } else {
                    sm.maskField(grp, col.getSqlName());
                }
            }
        }
        qbJTable.refreshSqlPreview(false);
        updateJTableUI();
    }

    private void setSelectedFieldsPK(boolean isPK) {
        // Meta_Table m = qbJTable.getModel().getTbean().getTableDetail();
        for (int row : qbJTable.getSelectedRows()) {
            I_WfColumn col = (I_WfColumn) qbJTable.getModel().getValueAt(row, 0);
            if (col != null) {
                col.setPk(isPK);
                qbJTable.getModel().fillRow(row, col);
            }
        }
    }
}
