/*
 * BcaTool_LocateClassPanel.java
 *
 * Created on 2007年8月10日, 下午3:28
 */
package com.bca.toolkit.top.tools.util;

import com.bca.api.pub.Ret;
import com.bca.pub.tools.Stringtool;
import com.bca.pub.tools.Toolfunc;
import com.bca.templ.pub.AbstractStudioApp;
import java.util.Random;

/**
 *
 * @author pxz
 */
public class BcaTool_RandomForm extends javax.swing.JPanel {

    final static com.bca.tools.log.Log log = com.bca.tools.log.LogFactory.getLog();
    final Ret ret = new Ret();
    final AbstractStudioApp app = AbstractStudioApp.getApp();

    /**
     * Creates new form BcaTool_LocateClassPanel
     */
    public BcaTool_RandomForm() {
        initComponents();

//        wfinit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        letterCheck = new javax.swing.JCheckBox();
        numCheck = new javax.swing.JCheckBox();
        symbol1_check = new javax.swing.JCheckBox();
        symbol2_check = new javax.swing.JCheckBox();
        lenField = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        targetPane = new javax.swing.JTextPane();
        copyButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        jLabel1.setText("随机码长度:");

        letterCheck.setSelected(true);
        letterCheck.setText("字母");

        numCheck.setSelected(true);
        numCheck.setText("数字");

        symbol1_check.setText("基础符号");

        symbol2_check.setText("扩展符号");

        lenField.setValue(32);

        jLabel3.setText("目标随机码:");

        jScrollPane2.setViewportView(targetPane);

        copyButton.setText("复制到剪贴板");
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        createButton.setText("生成");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copyButton))
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lenField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(letterCheck)
                        .addGap(4, 4, 4)
                        .addComponent(numCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(symbol1_check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(symbol2_check)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letterCheck)
                    .addComponent(symbol1_check)
                    .addComponent(numCheck)
                    .addComponent(symbol2_check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(copyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        int strLen = (Integer) this.lenField.getValue();
        final Random random = new Random();
        char[] bb = new char[strLen];
        for (int i = 0; i < strLen; i++) {
            int r1 = random.nextInt();
            int r = r1 & 0xff;
            while (!checkRandomChar(r)) {
                r1 = random.nextInt();
                r = r1 & 0xff;
            }
            bb[i] = (char) r;
        }
        targetPane.setText(new String(bb));
    }//GEN-LAST:event_createButtonActionPerformed

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        Stringtool.copyToClipboard(targetPane.getText());
    }//GEN-LAST:event_copyButtonActionPerformed
    final Object[] basicSymbols = new Object[]{'_'};

    private boolean checkRandomChar(int r) {
//        int r = r1 & 0xff;
        if ((r & 0x80) != 0 || r == 0) {
            return false;
        }
        boolean b;
        if (this.letterCheck.isSelected()) {
            b = Character.isLetter(r);
            if (b) {
                return true;
            }
        }
        if (this.numCheck.isSelected()) {
            b = Character.isDigit(r);
            if (b) {
                return true;
            }
        }
        if (symbol1_check.isSelected()) {
            b = Toolfunc.isArrayContainsObj(basicSymbols, r);
            if (b) {
                return true;
            }
        }
        if (this.symbol2_check.isSelected()) {
            b = Character.isTitleCase(r);
            if (b) {
                return true;
            }
        }
        return false;
    }
//    final String CR = "\r\n";
//    Map<Integer, WfProcessBean> processes = null;
//    private void wfinit() {
////        Uitool.setFileDropTarget(flowaField);
////        Uitool.setFileDropTarget(flowbField);
////
////        final LineNumberHeaderView lnheadView = new LineNumberHeaderView(this.resultPane.getFont());
////        this.jScrollPane1.setRowHeaderView(lnheadView);
////        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton copyButton;
    javax.swing.JButton createButton;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel3;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JSpinner lenField;
    javax.swing.JCheckBox letterCheck;
    javax.swing.JCheckBox numCheck;
    javax.swing.JCheckBox symbol1_check;
    javax.swing.JCheckBox symbol2_check;
    javax.swing.JTextPane targetPane;
    // End of variables declaration//GEN-END:variables
}
