/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package microservice_framework.newboncproject;

import microservice_framework.baseFrames.BaseDialog;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.JFrame;

/**
 *
 * @author ur
 */
public class SettingsDialog_3 extends BaseDialog {

    private int FRAMEHEIGHT;
    private int FRAMEWIDTH;

    /**
     * @return the settingsDialog_4
     */
    public SettingsDialog_4 getSettingsDialog_4() {
        return settingsDialog_4;
    }

    /**
     * @param settingsDialog_4 the settingsDialog_4 to set
     */
    public void setSettingsDialog_4(SettingsDialog_4 settingsDialog_4) {
        this.settingsDialog_4 = settingsDialog_4;
    }

    /**
     * @return the settingsDialog_2
     */
    public SettingsDialog_2 getSettingsDialog_2() {
        return settingsDialog_2;
    }

    /**
     * @param settingsDialog_2 the settingsDialog_2 to set
     */
    public void setSettingsDialog_2(SettingsDialog_2 settingsDialog_2) {
        this.settingsDialog_2 = settingsDialog_2;
    }
    private SettingsDialog_2 settingsDialog_2;
    private SettingsDialog_4 settingsDialog_4;
    private JTextField[] tf;
    /** Creates new form SettingsDialog_3 */
    public SettingsDialog_3() {
        initComponents();
        wfinit();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        topLabel1 = new javax.swing.JLabel();
        topLabel2 = new javax.swing.JLabel();
        topLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cancelButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainSourcePanel = new javax.swing.JPanel();
        serverNameTFD = new javax.swing.JTextField();
        mainURLLabel = new javax.swing.JLabel();
        mainTypeLabel = new javax.swing.JLabel();
        frontVersionCBox = new javax.swing.JComboBox();
        mainAccountLabel = new javax.swing.JLabel();
        serviceURLTFD = new javax.swing.JTextField();
        mainPswLabel = new javax.swing.JLabel();
        cacheURLTFD = new javax.swing.JTextField();
        frameBox = new javax.swing.JCheckBox();
        defaultPageTFD = new javax.swing.JTextField();
        mainTypeLabel1 = new javax.swing.JLabel();
        cacheBox = new javax.swing.JCheckBox();
        mainTypeLabel2 = new javax.swing.JLabel();
        urlPrefixTFD = new javax.swing.JTextField();
        mainTypeLabel3 = new javax.swing.JLabel();
        loginURLTFD = new javax.swing.JTextField();
        securityBox = new javax.swing.JCheckBox();
        mainTypeLabel4 = new javax.swing.JLabel();
        cacheVersionCBox = new javax.swing.JComboBox();
        swaggerBox = new javax.swing.JCheckBox();
        deploymentWayBox = new javax.swing.JCheckBox();
        unitTestTFD = new javax.swing.JCheckBox();
        mserviceManage = new javax.swing.JCheckBox();
        mserviceRD = new javax.swing.JCheckBox();
        mserviceURLLabel = new javax.swing.JLabel();
        visiteAddressTFD = new javax.swing.JTextField();
        mainTypeLabel6 = new javax.swing.JLabel();
        registerAddressTFD = new javax.swing.JTextField();

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        topLabel1.setFont(new java.awt.Font("����", 1, 12)); // NOI18N
        topLabel1.setText("MicroService Project");

        topLabel2.setText("ѡ����������������������Ϣ��");

        topLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microservice_framework/images/open_file.png"))); // NOI18N
        topLabel3.setMinimumSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(topLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(topLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addComponent(topLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(topLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.setEnabled(false);

        nextButton.setText("Next >");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        mainSourcePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("�������"));

        serverNameTFD.setEnabled(false);
        serverNameTFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverNameTFDActionPerformed(evt);
            }
        });

        mainURLLabel.setText("DefaultPage:");

        mainTypeLabel.setText("ServerName:");

        frontVersionCBox.setEnabled(false);

        mainAccountLabel.setText("SecurityServiceURL:");

        serviceURLTFD.setEnabled(false);

        mainPswLabel.setText("URL:");

        cacheURLTFD.setEnabled(false);

        frameBox.setText("ǰ�˿��");
        frameBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                frameBoxStateChanged(evt);
            }
        });

        defaultPageTFD.setEnabled(false);
        defaultPageTFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultPageTFDActionPerformed(evt);
            }
        });

        mainTypeLabel1.setText("�汾:");

        cacheBox.setText("�������");
        cacheBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cacheBoxStateChanged(evt);
            }
        });
        cacheBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cacheBoxActionPerformed(evt);
            }
        });

        mainTypeLabel2.setText("CasServerUrlPrefix:");

        urlPrefixTFD.setEnabled(false);
        urlPrefixTFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlPrefixTFDActionPerformed(evt);
            }
        });

        mainTypeLabel3.setText("CasServerLoginURL:");

        loginURLTFD.setEnabled(false);
        loginURLTFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginURLTFDActionPerformed(evt);
            }
        });

        securityBox.setText("�Ż���ȫ");
        securityBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                securityBoxStateChanged(evt);
            }
        });
        securityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityBoxActionPerformed(evt);
            }
        });

        mainTypeLabel4.setText("�汾:");

        cacheVersionCBox.setEnabled(false);

        swaggerBox.setText("Swagger���");
        swaggerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swaggerBoxActionPerformed(evt);
            }
        });

        deploymentWayBox.setText("Docker����");
        deploymentWayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deploymentWayBoxActionPerformed(evt);
            }
        });

        unitTestTFD.setText("��Ԫ�������");
        unitTestTFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitTestTFDActionPerformed(evt);
            }
        });

        mserviceManage.setText("΢�������");
        mserviceManage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mserviceManageStateChanged(evt);
            }
        });
        mserviceManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mserviceManageActionPerformed(evt);
            }
        });

        mserviceRD.setText("����ע���뷢��");
        mserviceRD.setEnabled(false);
        mserviceRD.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mserviceRDStateChanged(evt);
            }
        });
        mserviceRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mserviceRDActionPerformed(evt);
            }
        });

        mserviceURLLabel.setText("������ʵ�ַ:");

        visiteAddressTFD.setEnabled(false);
        visiteAddressTFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visiteAddressTFDActionPerformed(evt);
            }
        });

        mainTypeLabel6.setText("ע�����ķ��ʵ�ַ:");

        registerAddressTFD.setEnabled(false);
        registerAddressTFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerAddressTFDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainSourcePanelLayout = new javax.swing.GroupLayout(mainSourcePanel);
        mainSourcePanel.setLayout(mainSourcePanelLayout);
        mainSourcePanelLayout.setHorizontalGroup(
            mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainSourcePanelLayout.createSequentialGroup()
                        .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mainURLLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainTypeLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(mainTypeLabel4)
                            .addComponent(mainPswLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cacheVersionCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cacheURLTFD)
                            .addGroup(mainSourcePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(serviceURLTFD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                                    .addComponent(loginURLTFD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(defaultPageTFD, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(24, 24, 24))
                    .addGroup(mainSourcePanelLayout.createSequentialGroup()
                        .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(unitTestTFD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(swaggerBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deploymentWayBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mserviceManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainSourcePanelLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(mserviceRD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(frameBox)
                            .addComponent(securityBox)
                            .addComponent(cacheBox)
                            .addGroup(mainSourcePanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mainTypeLabel6)
                                    .addComponent(mserviceURLLabel))
                                .addGap(18, 18, 18)
                                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(registerAddressTFD, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(visiteAddressTFD)))
                            .addGroup(mainSourcePanelLayout.createSequentialGroup()
                                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mainTypeLabel2)
                                    .addGroup(mainSourcePanelLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(mainTypeLabel1))
                                    .addComponent(mainTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(serverNameTFD, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(frontVersionCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(urlPrefixTFD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addGap(2, 2, 2))
        );
        mainSourcePanelLayout.setVerticalGroup(
            mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainSourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frontVersionCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainSourcePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(serverNameTFD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTypeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainSourcePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(urlPrefixTFD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTypeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainSourcePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(loginURLTFD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainURLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultPageTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceURLTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cacheBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cacheVersionCBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainTypeLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainPswLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cacheURLTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(swaggerBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitTestTFD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deploymentWayBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mserviceManage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mserviceRD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mserviceURLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visiteAddressTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTypeLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerAddressTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(mainSourcePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextButton)
                        .addGap(42, 42, 42)
                        .addComponent(finishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(finishButton)
                        .addComponent(cancelButton))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        setVisible(false);
        if(settingsDialog_4==null){
            settingsDialog_4=new SettingsDialog_4();
            settingsDialog_4.setSettingsDialog_3(this);
        }
        settingsDialog_4.setSize((int) (getSCREENWIDTH()/3), (int) (getSCREENHEIGHT()/1.18));
        settingsDialog_4.setLocation(getLocation());
        settingsDialog_4.setVisible(true);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        if(settingsDialog_2!=null){
            settingsDialog_2.setLocation(getLocation());
            settingsDialog_2.setVisible(true);
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void serverNameTFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverNameTFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverNameTFDActionPerformed

    private void frameBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_frameBoxStateChanged
        getFrontVersionCBox().setEnabled(getFrameBox().isSelected());
    }//GEN-LAST:event_frameBoxStateChanged

    private void defaultPageTFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultPageTFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defaultPageTFDActionPerformed

    private void cacheBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cacheBoxStateChanged
        getCacheVersionCBox().setEnabled(getCacheBox().isSelected());
        getCacheURLTFD().setEnabled(getCacheBox().isSelected());
        checkEssentialItems();
    }//GEN-LAST:event_cacheBoxStateChanged

    private void cacheBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cacheBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cacheBoxActionPerformed

    private void urlPrefixTFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlPrefixTFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlPrefixTFDActionPerformed

    private void loginURLTFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginURLTFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginURLTFDActionPerformed

    private void securityBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_securityBoxStateChanged
        boolean f=getSecurityBox().isSelected();
        getServerNameTFD().setEnabled(f);
        getUrlPrefixTFD().setEnabled(f);
        getLoginURLTFD().setEnabled(f);
        getDefaultPageTFD().setEnabled(f);
        getServiceURLTFD().setEnabled(f);
        checkEssentialItems();
    }//GEN-LAST:event_securityBoxStateChanged

    private void securityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityBoxActionPerformed

    private void swaggerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swaggerBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_swaggerBoxActionPerformed

    private void deploymentWayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deploymentWayBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deploymentWayBoxActionPerformed

    private void unitTestTFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitTestTFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitTestTFDActionPerformed

    private void mserviceManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mserviceManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mserviceManageActionPerformed

    private void mserviceRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mserviceRDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mserviceRDActionPerformed

    private void visiteAddressTFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visiteAddressTFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visiteAddressTFDActionPerformed

    private void registerAddressTFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerAddressTFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerAddressTFDActionPerformed
//΢�������ѡ��
    private void mserviceManageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mserviceManageStateChanged
        mserviceRD.setEnabled(mserviceManage.isSelected());
    }//GEN-LAST:event_mserviceManageStateChanged
//����ע���뷢�ָ�ѡ��
    private void mserviceRDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mserviceRDStateChanged
        visiteAddressTFD.setEnabled(mserviceRD.isSelected());
        registerAddressTFD.setEnabled(mserviceRD.isSelected());
    }//GEN-LAST:event_mserviceRDStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsDialog_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JCheckBox cacheBox;
    private javax.swing.JTextField cacheURLTFD;
    private javax.swing.JComboBox cacheVersionCBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField defaultPageTFD;
    private javax.swing.JCheckBox deploymentWayBox;
    private javax.swing.JButton finishButton;
    private javax.swing.JCheckBox frameBox;
    private javax.swing.JComboBox frontVersionCBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField loginURLTFD;
    private javax.swing.JLabel mainAccountLabel;
    private javax.swing.JLabel mainPswLabel;
    private javax.swing.JPanel mainSourcePanel;
    private javax.swing.JLabel mainTypeLabel;
    private javax.swing.JLabel mainTypeLabel1;
    private javax.swing.JLabel mainTypeLabel2;
    private javax.swing.JLabel mainTypeLabel3;
    private javax.swing.JLabel mainTypeLabel4;
    private javax.swing.JLabel mainTypeLabel6;
    private javax.swing.JLabel mainURLLabel;
    private javax.swing.JCheckBox mserviceManage;
    private javax.swing.JCheckBox mserviceRD;
    private javax.swing.JLabel mserviceURLLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField registerAddressTFD;
    private javax.swing.JCheckBox securityBox;
    private javax.swing.JTextField serverNameTFD;
    private javax.swing.JTextField serviceURLTFD;
    private javax.swing.JCheckBox swaggerBox;
    private javax.swing.JLabel topLabel1;
    private javax.swing.JLabel topLabel2;
    private javax.swing.JLabel topLabel3;
    private javax.swing.JCheckBox unitTestTFD;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JTextField urlPrefixTFD;
    private javax.swing.JTextField visiteAddressTFD;
    // End of variables declaration//GEN-END:variables

    private void wfinit() {
        changeSwingLooksAndFeels();
        setSize((int) (getSCREENWIDTH()/3), (int) (getSCREENHEIGHT()/1.18));
        FRAMEHEIGHT=getHeight();
        FRAMEWIDTH=getWidth();
        tf=new JTextField[]{getServerNameTFD(), getUrlPrefixTFD(), getLoginURLTFD(), getDefaultPageTFD(), getServiceURLTFD(), getCacheURLTFD()};
        for(JTextField t:tf){
             if(getSCREENHEIGHT()>800) {
                 t.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.9), FRAMEHEIGHT/32));
             }else{
                 t.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.9), FRAMEHEIGHT/32));
             }
         }
        if(getSCREENHEIGHT()>800){
                upperPanel.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.08), FRAMEHEIGHT/10));  //���ϱߵ���壬��ʾ�ļ���ͼ��
                topLabel2.setPreferredSize(new Dimension((int)(upperPanel.getPreferredSize().width/2), (int)(upperPanel.getPreferredSize().height/2.5)));
                jScrollPane1.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.08), (int)(FRAMEHEIGHT/1.4)));   //�����
                getCacheVersionCBox().setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.7), FRAMEHEIGHT/32));
        }else{
                upperPanel.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.1),(int)(FRAMEHEIGHT/12)));
                topLabel2.setPreferredSize(new Dimension((int)(upperPanel.getPreferredSize().width/5*4), (int)(upperPanel.getPreferredSize().height/2.5)));
                topLabel3.setPreferredSize(new Dimension((int)(upperPanel.getPreferredSize().width/5), (int)(upperPanel.getPreferredSize().height/5)));
                jScrollPane1.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.08), (int)(FRAMEHEIGHT/1.5)));  //�����
                getCacheVersionCBox().setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.7), FRAMEHEIGHT/32));
        }
       // initComponentsOnOwn();
        URL url=this.getClass().getResource("/microservice_framework/images/open_file.png");
        Image image = Toolkit.getDefaultToolkit().getImage(url);
        if(getSCREENHEIGHT()<=800)
            image=image.getScaledInstance(35, -1, Image.SCALE_DEFAULT);
        topLabel3.setIcon(new ImageIcon(image));
        getFrontVersionCBox().removeAllItems();
        getFrontVersionCBox().addItem("EPM-UI 0.4.4");
        getFrontVersionCBox().addItem("thymeleaf");
        getCacheVersionCBox().removeAllItems();
        getCacheVersionCBox().addItem("0.0.1-SNAPSHOT");
        for(JTextField t:tf){
            t.addFocusListener(new FocusListener(){
                @Override
                public void focusGained(FocusEvent e) {
                    checkEssentialItems();
                }

                @Override
                public void focusLost(FocusEvent e) {
                    checkEssentialItems();
                }
                
            });
            t.getDocument().addDocumentListener(new DocumentListener(){
                @Override
                public void insertUpdate(DocumentEvent e) {
                   checkEssentialItems();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    checkEssentialItems();
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    checkEssentialItems();
                }
                
            });
        }
        
    }
    //��дһ��У����
    private void checkEssentialItems(){
        //�������Ż���ȫУ��
        if(getSecurityBox().isSelected()){
            if(isTFDEmpty(getServerNameTFD())){  //ServerNameУ��
                setIconForWrong();
                topLabel2.setText("��������Ч��ServerName");
                nextButton.setEnabled(false);
                return;
            }else if(isTFDEmpty(getUrlPrefixTFD())){  //CasServerUrlPrefixУ��
                setIconForWrong();
                topLabel2.setText("��������Ч��CasServerUrlPrefix");
                nextButton.setEnabled(false);
                return;
            }else if(isTFDEmpty(getLoginURLTFD())){  //CasServerLoginURLУ��
                setIconForWrong();
                topLabel2.setText("��������Ч��CasServerLoginURL");
                nextButton.setEnabled(false);
                return;
            }else if(isTFDEmpty(getDefaultPageTFD())){  //defaultPageУ��
                setIconForWrong();
                topLabel2.setText("��������Ч��defaultPage");
                nextButton.setEnabled(false);
                return;
            }else if(isTFDEmpty(getServiceURLTFD())){  //SecurityServiceURLУ��
                setIconForWrong();
                topLabel2.setText("��������Ч��SecurityServiceURL");
                nextButton.setEnabled(false);
                return;
            }
          //�Ż���ȫУ�����
          // �������У��
          if(getCacheBox().isSelected()){
              if(isTFDEmpty(getCacheURLTFD())){
                setIconForWrong();
                topLabel2.setText("��������Ч�Ļ������URL");
                nextButton.setEnabled(false);
                return;
              }
          }
          //�������У�����
          
        }
        topLabel2.setIcon(null);
        topLabel2.setText("ѡ����������������������Ϣ��");
        nextButton.setEnabled(true);
    }
    /**
     * Ϊ��ʾ��ǩ���ô���ͼ��
     */
    public void setIconForWrong(){
                URL url=this.getClass().getResource("/microservice_framework/images/wrong_16px_.png");
                Image image = Toolkit.getDefaultToolkit().getImage(url);
                topLabel2.setIcon(new ImageIcon(image));
    }
    /*
    *У���ı����Ƿ�Ϊ��
    */
    private boolean isTFDEmpty(JTextField t){
        return t.getText()==null||t.getText().equals("");
    }

    private void initComponentsOnOwn() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topLabel1.setFont(new java.awt.Font("����", 1, 12)); // NOI18N
        topLabel1.setText("MicroService Project");

        topLabel2.setText("ѡ����������������������Ϣ��");

        topLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open_file.png"))); // NOI18N

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(topLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(topLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addComponent(topLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(topLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.setEnabled(false);

        nextButton.setText("Next >");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        mainSourcePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("�������"));

        getServerNameTFD().setEnabled(false);
        getServerNameTFD().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverNameTFDActionPerformed(evt);
            }
        });

        mainURLLabel.setText("DefaultPage:");

        mainTypeLabel.setText("ServerName:");

        getFrontVersionCBox().setEnabled(false);

        mainAccountLabel.setText("SecurityServiceURL:");

        getServiceURLTFD().setEnabled(false);

        mainPswLabel.setText("URL:");

        getCacheURLTFD().setEnabled(false);

        getFrameBox().setText("ǰ�˿��");
        getFrameBox().addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                frameBoxStateChanged(evt);
            }
        });

        getDefaultPageTFD().setEnabled(false);
        getDefaultPageTFD().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultPageTFDActionPerformed(evt);
            }
        });

        mainTypeLabel1.setText("�汾:");

        getCacheBox().setText("�������");
        getCacheBox().addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cacheBoxStateChanged(evt);
            }
        });
        getCacheBox().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cacheBoxActionPerformed(evt);
            }
        });

        mainTypeLabel2.setText("CasServerUrlPrefix:");

        getUrlPrefixTFD().setEnabled(false);
        getUrlPrefixTFD().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlPrefixTFDActionPerformed(evt);
            }
        });

        mainTypeLabel3.setText("CasServerLoginURL:");

        getLoginURLTFD().setEnabled(false);
        getLoginURLTFD().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginURLTFDActionPerformed(evt);
            }
        });

        getSecurityBox().setText("�Ż���ȫ");
        getSecurityBox().addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                securityBoxStateChanged(evt);
            }
        });
        getSecurityBox().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityBoxActionPerformed(evt);
            }
        });

        mainTypeLabel4.setText("�汾:");

        getCacheVersionCBox().setEnabled(false);

        getSwaggerBox().setText("Swagger���");
        getSwaggerBox().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swaggerBoxActionPerformed(evt);
            }
        });

        getDeploymentWayBox().setText("Docker����");
        getDeploymentWayBox().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deploymentWayBoxActionPerformed(evt);
            }
        });

        getUnitTestTFD().setText("��Ԫ�������");
        getUnitTestTFD().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitTestTFDActionPerformed(evt);
            }
        });

        getMserviceManage().setText("΢�������");
        getMserviceManage().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mserviceManageActionPerformed(evt);
            }
        });

        getMserviceRD().setText("����ע���뷢��");
        getMserviceRD().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });

        getMserviceURLCBox().setText("������ʵ�ַ:");

        getVisiteAddressTFD1().setEnabled(false);
        getVisiteAddressTFD1().addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });

        mainTypeLabel6.setText("ע�����ķ��ʵ�ַ:");

        getVisiteAddressTFD2().setEnabled(false);
        getVisiteAddressTFD2().addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });

        javax.swing.GroupLayout mainSourcePanelLayout = new javax.swing.GroupLayout(mainSourcePanel);
        mainSourcePanel.setLayout(mainSourcePanelLayout);
        mainSourcePanelLayout.setHorizontalGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(getUnitTestTFD(), javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getSwaggerBox(), javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getDeploymentWayBox(), javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getMserviceManage(), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainSourcePanelLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(getMserviceRD(), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mainSourcePanelLayout.createSequentialGroup()
                            .addComponent(mainTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(getServerNameTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainSourcePanelLayout.createSequentialGroup()
                            .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mainTypeLabel2)
                                .addGroup(mainSourcePanelLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(mainTypeLabel1)))
                            .addGap(43, 43, 43)
                            .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(getFrontVersionCBox(), 0, javax.swing.GroupLayout.PREFERRED_SIZE, Short.MAX_VALUE)
                                .addComponent(getUrlPrefixTFD())))
                        .addComponent(getFrameBox())
                        .addComponent(getSecurityBox())
                        .addComponent(getCacheBox())
                        .addGroup(mainSourcePanelLayout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mainTypeLabel6)
                                .addComponent(getMserviceURLCBox()))
                            .addGap(18, 18, 18)
                            .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(getVisiteAddressTFD1())
                                .addComponent(getVisiteAddressTFD2())))
                        .addGroup(mainSourcePanelLayout.createSequentialGroup()
                            .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(mainURLLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mainTypeLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(mainTypeLabel4)
                                .addComponent(mainPswLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(9, 9, 9)
                            .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(getServiceURLTFD(), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, Short.MAX_VALUE)
                                    .addComponent(getDefaultPageTFD())
                                    .addComponent(getLoginURLTFD(), javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(getCacheVersionCBox(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(getCacheURLTFD())))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        mainSourcePanelLayout.setVerticalGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainSourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getFrameBox())
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getFrontVersionCBox(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getSecurityBox())
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getServerNameTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTypeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getUrlPrefixTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTypeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getLoginURLTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainURLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDefaultPageTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getServiceURLTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getCacheBox())
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getCacheVersionCBox(), javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainTypeLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainPswLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getCacheURLTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(getSwaggerBox())
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getUnitTestTFD())
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getDeploymentWayBox())
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getMserviceManage())
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getMserviceRD())
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getMserviceURLCBox(), javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getVisiteAddressTFD1(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTypeLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getVisiteAddressTFD2(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(mainSourcePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(796, 796, 796)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextButton)
                        .addGap(42, 42, 42)
                        .addComponent(finishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(finishButton)
                        .addComponent(cancelButton)))
                .addGap(39, 39, 39))
        );

    }

    /**
     * @return the frontVersionCBox
     */
    public javax.swing.JComboBox getFrontVersionCBox() {
        return frontVersionCBox;
    }

    /**
     * @param frontVersionCBox the frontVersionCBox to set
     */
    public void setFrontVersionCBox(javax.swing.JComboBox frontVersionCBox) {
        this.frontVersionCBox = frontVersionCBox;
    }

    /**
     * @return the frameBox
     */
    public javax.swing.JCheckBox getFrameBox() {
        return frameBox;
    }

    /**
     * @param frameBox the frameBox to set
     */
    public void setFrameBox(javax.swing.JCheckBox frameBox) {
        this.frameBox = frameBox;
    }

    /**
     * @return the securityBox
     */
    public javax.swing.JCheckBox getSecurityBox() {
        return securityBox;
    }

    /**
     * @param securityBox the securityBox to set
     */
    public void setSecurityBox(javax.swing.JCheckBox securityBox) {
        this.securityBox = securityBox;
    }

    /**
     * @return the serverNameTFD
     */
    public javax.swing.JTextField getServerNameTFD() {
        return serverNameTFD;
    }

    /**
     * @param serverNameTFD the serverNameTFD to set
     */
    public void setServerNameTFD(javax.swing.JTextField serverNameTFD) {
        this.serverNameTFD = serverNameTFD;
    }

    /**
     * @return the urlPrefixTFD
     */
    public javax.swing.JTextField getUrlPrefixTFD() {
        return urlPrefixTFD;
    }

    /**
     * @param urlPrefixTFD the urlPrefixTFD to set
     */
    public void setUrlPrefixTFD(javax.swing.JTextField urlPrefixTFD) {
        this.urlPrefixTFD = urlPrefixTFD;
    }

    /**
     * @return the loginURLTFD
     */
    public javax.swing.JTextField getLoginURLTFD() {
        return loginURLTFD;
    }

    /**
     * @param loginURLTFD the loginURLTFD to set
     */
    public void setLoginURLTFD(javax.swing.JTextField loginURLTFD) {
        this.loginURLTFD = loginURLTFD;
    }

    /**
     * @return the defaultPageTFD
     */
    public javax.swing.JTextField getDefaultPageTFD() {
        return defaultPageTFD;
    }

    /**
     * @param defaultPageTFD the defaultPageTFD to set
     */
    public void setDefaultPageTFD(javax.swing.JTextField defaultPageTFD) {
        this.defaultPageTFD = defaultPageTFD;
    }

    /**
     * @return the serviceURLTFD
     */
    public javax.swing.JTextField getServiceURLTFD() {
        return serviceURLTFD;
    }

    /**
     * @param serviceURLTFD the serviceURLTFD to set
     */
    public void setServiceURLTFD(javax.swing.JTextField serviceURLTFD) {
        this.serviceURLTFD = serviceURLTFD;
    }

    /**
     * @return the cacheBox
     */
    public javax.swing.JCheckBox getCacheBox() {
        return cacheBox;
    }

    /**
     * @param cacheBox the cacheBox to set
     */
    public void setCacheBox(javax.swing.JCheckBox cacheBox) {
        this.cacheBox = cacheBox;
    }

    /**
     * @return the cacheVersionCBox
     */
    public javax.swing.JComboBox getCacheVersionCBox() {
        return cacheVersionCBox;
    }

    /**
     * @param cacheVersionCBox the cacheVersionCBox to set
     */
    public void setCacheVersionCBox(javax.swing.JComboBox cacheVersionCBox) {
        this.cacheVersionCBox = cacheVersionCBox;
    }

    /**
     * @return the cacheURLTFD
     */
    public javax.swing.JTextField getCacheURLTFD() {
        return cacheURLTFD;
    }

    /**
     * @param cacheURLTFD the cacheURLTFD to set
     */
    public void setCacheURLTFD(javax.swing.JTextField cacheURLTFD) {
        this.cacheURLTFD = cacheURLTFD;
    }

    /**
     * @return the swaggerBox
     */
    public javax.swing.JCheckBox getSwaggerBox() {
        return swaggerBox;
    }

    /**
     * @param swaggerBox the swaggerBox to set
     */
    public void setSwaggerBox(javax.swing.JCheckBox swaggerBox) {
        this.swaggerBox = swaggerBox;
    }

    /**
     * @return the unitTestTFD
     */
    public javax.swing.JCheckBox getUnitTestTFD() {
        return unitTestTFD;
    }

    /**
     * @param unitTestTFD the unitTestTFD to set
     */
    public void setUnitTestTFD(javax.swing.JCheckBox unitTestTFD) {
        this.unitTestTFD = unitTestTFD;
    }

    /**
     * @return the deploymentWayBox
     */
    public javax.swing.JCheckBox getDeploymentWayBox() {
        return deploymentWayBox;
    }

    /**
     * @param deploymentWayBox the deploymentWayBox to set
     */
    public void setDeploymentWayBox(javax.swing.JCheckBox deploymentWayBox) {
        this.deploymentWayBox = deploymentWayBox;
    }

    /**
     * @return the mserviceManage
     */
    public javax.swing.JCheckBox getMserviceManage() {
        return mserviceManage;
    }

    /**
     * @param mserviceManage the mserviceManage to set
     */
    public void setMserviceManage(javax.swing.JCheckBox mserviceManage) {
        this.mserviceManage = mserviceManage;
    }

    /**
     * @return the mserviceRD
     */
    public javax.swing.JCheckBox getMserviceRD() {
        return mserviceRD;
    }

    /**
     * @param mserviceRD the mserviceRD to set
     */
    public void setMserviceRD(javax.swing.JCheckBox mserviceRD) {
        this.mserviceRD = mserviceRD;
    }

    /**
     * @return the mserviceURLCBox
     */
    public javax.swing.JLabel getMserviceURLCBox() {
        return mserviceURLLabel;
    }

    /**
     * @param mserviceURLCBox the mserviceURLCBox to set
     */
    public void setMserviceURLCBox(javax.swing.JLabel mserviceURLCBox) {
        this.mserviceURLLabel = mserviceURLCBox;
    }

    /**
     * @return the visiteAddressTFD1
     */
    public javax.swing.JTextField getVisiteAddressTFD1() {
        return visiteAddressTFD;
    }

    /**
     * @param visiteAddressTFD1 the visiteAddressTFD1 to set
     */
    public void setVisiteAddressTFD1(javax.swing.JTextField visiteAddressTFD1) {
        this.visiteAddressTFD = visiteAddressTFD1;
    }

    /**
     * @return the visiteAddressTFD2
     */
    public javax.swing.JTextField getVisiteAddressTFD2() {
        return registerAddressTFD;
    }

    /**
     * @param visiteAddressTFD2 the visiteAddressTFD2 to set
     */
    public void setVisiteAddressTFD2(javax.swing.JTextField visiteAddressTFD2) {
        this.registerAddressTFD = visiteAddressTFD2;
    }
}
