/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package microservice_framework.newboncproject;

import microservice_framework.baseFrames.BaseDialog;
import static microservice_framework.baseFrames.BaseDialog.getSCREENHEIGHT;
import microservice_framework.getInput.DataSource;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.JFrame;

/**
 *
 * @author ur
 */
public class SettingsDialog_2 extends BaseDialog {

    /**
     * @return the settingsDialog_3
     */
    public SettingsDialog_3 getSettingsDialog_3() {
        return settingsDialog_3;
    }

    /**
     * @param settingsDialog_3 the settingsDialog_3 to set
     */
    public void setSettingsDialog_3(SettingsDialog_3 settingsDialog_3) {
        this.settingsDialog_3 = settingsDialog_3;
    }

    /**
     * @return the settingsDialog_1
     */
    public SettingsDialog_1 getSettingsDialog_1() {
        return settingsDialog_1;
    }

    /**
     * @param settingsDialog_1 the settingsDialog_1 to set
     */
    public void setSettingsDialog_1(SettingsDialog_1 settingsDialog_1) {
        this.settingsDialog_1 = settingsDialog_1;
    }
    private OtherSourcePanel otherSourcePanel;
    private JPanel containPanel;
    private Map<String, DataSource> otherSourcesDatas;
    private List<OtherSourcePanel> panels;
    private SettingsDialog_1 settingsDialog_1;
    private SettingsDialog_3 settingsDialog_3;
    private int FRAMEHEIGHT; //����߶�
    private int FRAMEWIDTH;  //������
    private JTextField[] otherTf;
    /**
     * Creates new form SettingsDialog_2
     */
    public SettingsDialog_2() {
        initComponents();
        wfinit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        upperPanel = new javax.swing.JPanel();
        topLabel1 = new javax.swing.JLabel();
        topLabel1.setFont(new Font("����", Font.PLAIN, 12));
        topLabel2 = new javax.swing.JLabel();
        topLabel2.setFont(new Font("����", Font.PLAIN, 12));
        topLabel3 = new javax.swing.JLabel();
        mainSourcePanel = new javax.swing.JPanel();
        mainURLTFD = new javax.swing.JTextField();
        mainURLLabel = new javax.swing.JLabel();
        mainURLLabel.setFont(new Font("����", Font.PLAIN, 12));
        mainTypeLabel = new javax.swing.JLabel();
        mainTypeLabel.setFont(new Font("����", Font.PLAIN, 12));
        mainTypeBox = new javax.swing.JComboBox();
        mainTypeBox.setFont(new Font("����", Font.PLAIN, 12));
        mainAccountLabel = new javax.swing.JLabel();
        mainAccountLabel.setFont(new Font("����", Font.PLAIN, 12));
        mainAccountTFD = new javax.swing.JTextField();
        mainPswLabel = new javax.swing.JLabel();
        mainPswLabel.setFont(new Font("����", Font.PLAIN, 12));
        mainPswTFD = new javax.swing.JTextField();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        otherSourceLabel = new javax.swing.JLabel();
        otherSourceLabel.setFont(new Font("����", Font.PLAIN, 12));
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        otherSourceJSP = new javax.swing.JScrollPane();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        topLabel1.setFont(new java.awt.Font("����", 1, 12)); // NOI18N
        topLabel1.setText("MicroService Project");

        topLabel2.setText("��������Դ��Ϣ");

        topLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microservice_framework/images/open_file.png"))); // NOI18N
        topLabel3.setMinimumSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(topLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(topLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addComponent(topLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(topLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainSourcePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)), "������Դ"));

        mainURLLabel.setText("URL:");

        mainTypeLabel.setText("����Դ����:");

        mainAccountLabel.setText("�˻�:");

        mainPswLabel.setText("����:");

        mainPswTFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPswTFDActionPerformed(evt);
            }
        });

        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("ʾ����jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)))(CONNECT_DATA =(SID = orcl)))");
        jTextArea2.setWrapStyleWord(true);

        javax.swing.GroupLayout mainSourcePanelLayout = new javax.swing.GroupLayout(mainSourcePanel);
        mainSourcePanel.setLayout(mainSourcePanelLayout);
        mainSourcePanelLayout.setHorizontalGroup(
            mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSourcePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextArea2)
                    .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainSourcePanelLayout.createSequentialGroup()
                            .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mainTypeLabel)
                                .addComponent(mainURLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mainTypeBox, 0, 372, Short.MAX_VALUE)
                                .addComponent(mainURLTFD)))
                        .addGroup(mainSourcePanelLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(mainAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mainAccountTFD, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(mainPswLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mainPswTFD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainSourcePanelLayout.setVerticalGroup(
            mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainURLTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainURLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainAccountTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPswLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPswTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        otherSourceLabel.setText("��������Դ");

        deleteButton.setText("ɾ��");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setText("����");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next >");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.setEnabled(false);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        otherSourceJSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        otherSourceJSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        otherSourceJSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(otherSourceJSP))
                            .addComponent(mainSourcePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton)
                        .addGap(42, 42, 42)
                        .addComponent(finishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(otherSourceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton)
                        .addGap(30, 30, 30)
                        .addComponent(deleteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainSourcePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherSourceLabel)
                    .addComponent(addButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otherSourceJSP, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton))
                    .addComponent(finishButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        setVisible(false);
        if(settingsDialog_3==null){
            settingsDialog_3=new SettingsDialog_3();
            settingsDialog_3.setSettingsDialog_2(this);
        }
        settingsDialog_3.setSize((int) (getSCREENWIDTH()/3), (int) (getSCREENHEIGHT()/1.18));
       
        settingsDialog_3.setLocation(getLocation());
        settingsDialog_3.setVisible(true);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

    }//GEN-LAST:event_deleteButtonActionPerformed
//������ذ�ť������һ��ҳ��
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       setVisible(false);
       if(settingsDialog_1!=null) {
           settingsDialog_1.setLocation(getLocation());
           settingsDialog_1.setVisible(true);
       }
    }//GEN-LAST:event_backButtonActionPerformed

    private void mainPswTFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPswTFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainPswTFDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsDialog_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel mainAccountLabel;
    private javax.swing.JTextField mainAccountTFD;
    private javax.swing.JLabel mainPswLabel;
    private javax.swing.JTextField mainPswTFD;
    private javax.swing.JPanel mainSourcePanel;
    private javax.swing.JComboBox mainTypeBox;
    private javax.swing.JLabel mainTypeLabel;
    private javax.swing.JLabel mainURLLabel;
    private javax.swing.JTextField mainURLTFD;
    private javax.swing.JButton nextButton;
    private javax.swing.JScrollPane otherSourceJSP;
    private javax.swing.JLabel otherSourceLabel;
    private javax.swing.JLabel topLabel1;
    private javax.swing.JLabel topLabel2;
    private javax.swing.JLabel topLabel3;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
/*
*��ʼ��ҳ��
*/
    private void wfinit() {
        changeSwingLooksAndFeels();  //����ҳ����ͳߴ�
        setSize((int) (getSCREENWIDTH()/3), (int) (getSCREENHEIGHT()/1.18));
        
        FRAMEHEIGHT=getHeight();
        FRAMEWIDTH=getWidth();
        if(getSCREENHEIGHT()>800) {
                upperPanel.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.08), FRAMEHEIGHT/10));  //���ϱߵ���壬��ʾ�ļ���ͼ��
                topLabel2.setPreferredSize(new Dimension((int)(upperPanel.getPreferredSize().width/2), (int)(upperPanel.getPreferredSize().height/2.5)));
                getMainTypeBox().setPreferredSize(new Dimension((int)(FRAMEWIDTH/3*2.1), FRAMEHEIGHT/30));
                getMainPswTFD().setPreferredSize(new Dimension((int)(FRAMEWIDTH/9*2.6), FRAMEHEIGHT/30));
                getMainAccountTFD().setPreferredSize(new Dimension((int)(FRAMEWIDTH/9*2.6), FRAMEHEIGHT/30));
                otherSourceJSP.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.08), (int)(FRAMEHEIGHT/3.2)));//���±ߵ���壬��ʾ��������Դ
        }else {
                upperPanel.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.08), FRAMEHEIGHT/12));
                topLabel2.setPreferredSize(new Dimension((int)(upperPanel.getPreferredSize().width/5*4), (int)(upperPanel.getPreferredSize().height/2.5)));
                topLabel3.setPreferredSize(new Dimension((int)(upperPanel.getPreferredSize().width/5), (int)(upperPanel.getPreferredSize().height/5)));
                mainSourcePanel.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.08),(int)(FRAMEHEIGHT/3.2)));//������Դ���
                getMainTypeBox().setPreferredSize(new Dimension((int)(FRAMEWIDTH/3*1.9), FRAMEHEIGHT/30));
                getMainPswTFD().setPreferredSize(new Dimension((int)(FRAMEWIDTH/9*2.1), FRAMEHEIGHT/30));
                getMainAccountTFD().setPreferredSize(new Dimension((int)(FRAMEWIDTH/9*2.1), FRAMEHEIGHT/30));
                jTextArea2.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.2),(int)(FRAMEHEIGHT/10)));// ��ʾʾ�����ݵı�ǩ
                otherSourceJSP.setPreferredSize(new Dimension((int)(FRAMEWIDTH/1.08), (int)(FRAMEHEIGHT/3.7)));//���±ߵ���壬��ʾ��������Դ
        }
        
       // initComponentsOnOwn();
        URL url=this.getClass().getResource("/microservice_framework/images/open_file.png");
        Image image = Toolkit.getDefaultToolkit().getImage(url);
        if(getSCREENHEIGHT()<=800)
            image=image.getScaledInstance(35, -1, Image.SCALE_DEFAULT);
        topLabel3.setIcon(new ImageIcon(image));
        getMainTypeBox().removeAllItems();
        final String[] dataSources={"Oracle", "MySQL", "XCloud2.0.8"};
        for (String dataSource : dataSources) {
            getMainTypeBox().addItem(dataSource);
        }
        panels=new ArrayList<OtherSourcePanel>();  //��弯��
        
        containPanel=new JPanel(); //������������Դ���������
        
        addButton.addActionListener(new ActionListener(){
            @Override 
            public void actionPerformed(ActionEvent e) {
                containPanel.setLayout(new GridLayout(2*(panels.size()+1),1));  
                otherSourcePanel=new OtherSourcePanel();   //������������Դ���
                otherSourcePanel.getOtherKeyBox().addChangeListener(new ChangeListener(){
                    @Override
                    public void stateChanged(ChangeEvent e) {
                        for(OtherSourcePanel o:panels){
                             checkOtherSource(o);   //У����������Դ��Ϣ
                        }
                    }
                });
                //Ϊ��������Դ����ϵĿؼ���Ӽ�����
                otherTf=new JTextField[]{otherSourcePanel.getOtherKeyTFD(),otherSourcePanel.getOtherURLTFD(),
                                         otherSourcePanel.getOtherAccountTFD(),otherSourcePanel.getOtherPswTFD()};
                for(JTextField t:otherTf){
                    t.addFocusListener(new FocusListener(){
                        @Override
                        public void focusGained(FocusEvent e) {
                            for(OtherSourcePanel o:panels){
                             checkOtherSource(o);   //У����������Դ��Ϣ
                        }
                        }

                        @Override
                        public void focusLost(FocusEvent e) {
                            for(OtherSourcePanel o:panels){
                             checkOtherSource(o);   //У����������Դ��Ϣ
                        }
                        }
                    });
                    t.getDocument().addDocumentListener(new DocumentListener(){
                        @Override
                        public void insertUpdate(DocumentEvent e) {
                            for(OtherSourcePanel o:panels){
                             checkOtherSource(o);   //У����������Դ��Ϣ
                        }
                        }

                        @Override
                        public void removeUpdate(DocumentEvent e) {
                           for(OtherSourcePanel o:panels){
                             checkOtherSource(o);   //У����������Դ��Ϣ
                        }
                        }

                        @Override
                        public void changedUpdate(DocumentEvent e) {
                           for(OtherSourcePanel o:panels){
                             checkOtherSource(o);   //У����������Դ��Ϣ
                        }
                        }
                }); 
              } 
       //��������Դ���ؼ��ļ�����������
                panels.add(otherSourcePanel);
                containPanel.add(otherSourcePanel,-1);
                //��JPanel��ӵ�JScrollPane��
                otherSourceJSP.getViewport().setView(containPanel);
                for(OtherSourcePanel o:panels){
                    checkOtherSource(o);   //У����������Դ��Ϣ
                }
            }
            
        });
        deleteButton.addActionListener(new ActionListener(){
            @Override
            
            public void actionPerformed(ActionEvent e) {
                    int flag=0;
                    if(containPanel.getComponentCount()==0) return;
                            for(final OtherSourcePanel p:panels){
                                if(p==panels.get(panels.size()-1))
                                        flag=1;
                                if(p.getOtherKeyBox().isSelected()){
                                    
                                    EventQueue.invokeLater(new Runnable(){  //�����̣߳���ֹ����
                                        @Override
                                        public void run() {
                                            containPanel.remove(p);
                                            panels.remove(p);
                                            if(panels.isEmpty()){
                                                topLabel2.setIcon(null);
                                                topLabel2.setText("��������Դ��Ϣ");
                                                nextButton.setEnabled(true);
                                            }
                                        }
                                    });
                                }
                            }
                            if(flag==1){
                                EventQueue.invokeLater(new Runnable(){
                                    @Override
                                    public void run() {
                                         containPanel.removeAll();
                                         if(panels.isEmpty()) return;
                                        //ɾ��֮�����²��ù������
                                        for(final OtherSourcePanel p:panels){
                                            containPanel.add(p);
                                        }
                                    }
                                });
                                containPanel.repaint();    //����ɾ�����������ڴ�������ʾ��Ч������revalidate�����ӳ٣�ֻ�����������
                                //��JPanel��ӵ�JScrollPane��
                                otherSourceJSP.getViewport().setView(containPanel);
                            }
                           
                     
            }
        });
     }
    //��дһ��У������У����������Դ��Ϣ�Ƿ���ȷ
    private void checkOtherSource(OtherSourcePanel checkPanel){
            if(isTFDEmpty(checkPanel.getOtherKeyTFD())){  
                setIconForWrong();
                topLabel2.setText("��������������ԴKeyֵ��");
                nextButton.setEnabled(false);
            }else if(isTFDEmpty(checkPanel.getOtherURLTFD())){
                setIconForWrong();
                topLabel2.setText("��������������ԴURL��");
                nextButton.setEnabled(false);
            }else if(isTFDEmpty(checkPanel.getOtherAccountTFD())){
                setIconForWrong();
                topLabel2.setText("��������������Դ�˻���");
                nextButton.setEnabled(false);
            }else if(isTFDEmpty(checkPanel.getOtherPswTFD())){
                setIconForWrong();
                topLabel2.setText("��������������Դ���롣");
                nextButton.setEnabled(false);
            }else{
                topLabel2.setIcon(null);
                topLabel2.setText("��������Դ��Ϣ");
                nextButton.setEnabled(true);
            }
        
    }
    /**
     * Ϊ��ʾ��ǩ���ô���ͼ��
     */
    public void setIconForWrong(){
                URL url=this.getClass().getResource("/microservice_framework/images/wrong_16px_.png");
                Image image = Toolkit.getDefaultToolkit().getImage(url);
                topLabel2.setIcon(new ImageIcon(image));
    }
    /*
    *У���ı����Ƿ�Ϊ��
    */
    private boolean isTFDEmpty(JTextField t){
        return t.getText()==null||t.getText().equals("");
    }

    private void initComponentsOnOwn() {
        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topLabel1.setFont(new java.awt.Font("����", 1, 12)); // NOI18N
        topLabel1.setText("MicroService Project");

        topLabel2.setText("��������Դ��Ϣ");

        topLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microservice_framework/images/open_file.png"))); // NOI18N

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(topLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(topLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addComponent(topLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(topLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainSourcePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)), "������Դ"));

        mainURLLabel.setText("URL:");

        mainTypeLabel.setText("����Դ����:");

        mainAccountLabel.setText("�˻�:");

        mainPswLabel.setText("����:");

        getMainPswTFD().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPswTFDActionPerformed(evt);
            }
        });

        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("ʾ����jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)))(CONNECT_DATA =(SID = orcl)))");
        jTextArea2.setWrapStyleWord(true);

        javax.swing.GroupLayout mainSourcePanelLayout = new javax.swing.GroupLayout(mainSourcePanel);
        mainSourcePanel.setLayout(mainSourcePanelLayout);
        mainSourcePanelLayout.setHorizontalGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSourcePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainSourcePanelLayout.createSequentialGroup()
                        .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainTypeLabel)
                            .addComponent(mainURLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(getMainURLTFD())
                            .addComponent(getMainTypeBox(), 0, javax.swing.GroupLayout.PREFERRED_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextArea2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainSourcePanelLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(mainAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(getMainAccountTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)
                            .addComponent(mainPswLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(getMainPswTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainSourcePanelLayout.setVerticalGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getMainTypeBox(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getMainURLTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainURLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getMainAccountTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPswLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getMainPswTFD(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        otherSourceLabel.setText("��������Դ");

        deleteButton.setText("ɾ��");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setText("����");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next >");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.setEnabled(false);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        otherSourceJSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        otherSourceJSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        otherSourceJSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(otherSourceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton)
                        .addGap(30, 30, 30)
                        .addComponent(deleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextButton)
                        .addGap(42, 42, 42)
                        .addComponent(finishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainSourcePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(otherSourceJSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainSourcePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherSourceLabel)
                    .addComponent(addButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(otherSourceJSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton))
                    .addComponent(finishButton))
                .addContainerGap())
        );
    }

    /**
     * @return the mainTypeBox
     */
    public javax.swing.JComboBox getMainTypeBox() {
        return mainTypeBox;
    }

    /**
     * @param mainTypeBox the mainTypeBox to set
     */
    public void setMainTypeBox(javax.swing.JComboBox mainTypeBox) {
        this.mainTypeBox = mainTypeBox;
    }

    /**
     * @return the mainURLTFD
     */
    public javax.swing.JTextField getMainURLTFD() {
        return mainURLTFD;
    }

    /**
     * @param mainURLTFD the mainURLTFD to set
     */
    public void setMainURLTFD(javax.swing.JTextField mainURLTFD) {
        this.mainURLTFD = mainURLTFD;
    }

    /**
     * @return the mainAccountTFD
     */
    public javax.swing.JTextField getMainAccountTFD() {
        return mainAccountTFD;
    }

    /**
     * @param mainAccountTFD the mainAccountTFD to set
     */
    public void setMainAccountTFD(javax.swing.JTextField mainAccountTFD) {
        this.mainAccountTFD = mainAccountTFD;
    }

    /**
     * @return the mainPswTFD
     */
    public javax.swing.JTextField getMainPswTFD() {
        return mainPswTFD;
    }

    /**
     * @param mainPswTFD the mainPswTFD to set
     */
    public void setMainPswTFD(javax.swing.JTextField mainPswTFD) {
        this.mainPswTFD = mainPswTFD;
    }
    /**
    *��ȡ��������Դ����Ϊ��Ը��ӣ����Է�װ�ڱ�����
     * @return 
    */
    public HashMap<String, DataSource> obtainOtherSource(){
        if(panels.isEmpty()) return null;
        otherSourcesDatas=new HashMap<String, DataSource>();
        
        for(OtherSourcePanel p:panels){
            String key=p.getOtherKeyTFD().getText();
            DataSource value=new DataSource();
            value.setDataType((String)(p.getOtherTypeCBox().getSelectedItem()));
            value.setUrl(p.getOtherURLTFD().getText());
            value.setUsername(p.getOtherAccountTFD().getText());
            value.setPassword(p.getOtherPswTFD().getText());
            otherSourcesDatas.put(key, value);
        }
        return (HashMap<String, DataSource>) otherSourcesDatas;
    }
    }

