/*
 * BcaToolsTopComponent.java
 *
 * Created on 2008年10月18日, 下午7:31
 */
package com.bca.toolkit.top.tools;

import com.bca.toolkit.app.BcaToolkitFcSwitch;
import com.bca.studio.top.tools.GeorageCreaterDialog;
import com.bca.toolkit.app.BcaToolkit;
import com.bca.toolkit.top.tools.orm.BcaTool_PojoCreatePanel;
import com.bca.toolkit.top.tools.sql.BcaTool_SqlBuilderTopForm;
import javax.swing.SwingUtilities;

/**
 *
 * @author pxz
 */
public class BcaToolsTopComponent extends javax.swing.JPanel {

    private static BcaToolsTopComponent inst = null;

    public static BcaToolsTopComponent getInst() {
       // if (inst == null) {    每次都重新创建一个类，避免插件第二次启动时，显示上一次的页面
            inst = new BcaToolsTopComponent();
       // }
        return inst;
    }
    javax.swing.JPanel currentLoadingToolPanel = null;

    /**
     * Creates new form BcaToolsTopComponent
     */
    public BcaToolsTopComponent() {
        initComponents();
        // 先移去除“sql工厂”按钮，避免误会
        jToolBar1.remove(this.createPojoButton); 
       // if (BcaToolkitFcSwitch.codeFatory) {
            // createPojoButtonActionPerformed(null);
            sqlBuilderButtonActionPerformed(null);
       // }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        createPojoButton = new javax.swing.JToggleButton();
        sqlBuilderButton = new javax.swing.JToggleButton();
        jToolBar2 = new javax.swing.JToolBar();
        createPasswordCryptButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        buttonGroup1.add(createPojoButton);
        createPojoButton.setText("创建持久类"); // NOI18N
        createPojoButton.setFocusable(false);
        createPojoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createPojoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createPojoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPojoButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(createPojoButton);

        buttonGroup1.add(sqlBuilderButton);
        sqlBuilderButton.setText("SQL工厂");
        sqlBuilderButton.setFocusable(false);
        sqlBuilderButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sqlBuilderButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sqlBuilderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqlBuilderButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(sqlBuilderButton);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.CENTER);

        jToolBar2.setRollover(true);

        createPasswordCryptButton.setText("密码工厂"); // NOI18N
        createPasswordCryptButton.setFocusable(false);
        createPasswordCryptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createPasswordCryptButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createPasswordCryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPasswordCryptButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(createPasswordCryptButton);

        jPanel1.add(jToolBar2, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

private void createPojoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPojoButtonActionPerformed
//        if (currentActiveButton == createPojoButton) {
//            return;
//        }
//        if (currentActiveButton != null) {
//            currentActiveButton.setSelected(false);
//        }
    if (currentLoadingToolPanel instanceof BcaTool_PojoCreatePanel) {
        return;
    }
    if (currentLoadingToolPanel != null) {
        remove(currentLoadingToolPanel);
    }
    currentLoadingToolPanel = new BcaTool_PojoCreatePanel();
    add(currentLoadingToolPanel, java.awt.BorderLayout.CENTER);
    SwingUtilities.updateComponentTreeUI(this);

    createPojoButton.setSelected(true);
//        currentActiveButton = createPojoButton;
}//GEN-LAST:event_createPojoButtonActionPerformed

private void createPasswordCryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPasswordCryptButtonActionPerformed
    BcaToolkit app = BcaToolkit.getApp();

    GeorageCreaterDialog dlg = new GeorageCreaterDialog(app.getMainFrame());
    dlg.setBounds(app.getCenterBounds(dlg.getPreferredSize()));
    dlg.setVisible(true);
}//GEN-LAST:event_createPasswordCryptButtonActionPerformed

private void sqlBuilderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqlBuilderButtonActionPerformed
    //
    if (currentLoadingToolPanel instanceof BcaTool_SqlBuilderTopForm) {
        return;
    }
    if (currentLoadingToolPanel != null) {
        remove(currentLoadingToolPanel);
    }
    currentLoadingToolPanel = new BcaTool_SqlBuilderTopForm();
    add(currentLoadingToolPanel, java.awt.BorderLayout.CENTER);
    SwingUtilities.updateComponentTreeUI(this);

//    sqlBuilderButton.setSelected(true);
}//GEN-LAST:event_sqlBuilderButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton createPasswordCryptButton;
    private javax.swing.JToggleButton createPojoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToggleButton sqlBuilderButton;
    // End of variables declaration//GEN-END:variables
}
