/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.bca.toolkit.top.tools.sql.qb;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;

/**
 *
 * @author ur
 */
public class TableAliasAndModelNameDlg extends javax.swing.JDialog {
    private int status; //标识用户点击了哪个按钮：确认0/取消1
    String[] info = new String[2];  //储存用户输入的表别名和模型名称

    /**
     * Creates new form TableAliasAndModelNameDlg（系统自动生成的构造方法）
     */
    public TableAliasAndModelNameDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    //窗口弹出时实际调用的构造方法
    public TableAliasAndModelNameDlg(String messageTxt, String tableAlias){
        initComponents();
        wfinit(messageTxt, tableAlias);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tableAliasTextField = new javax.swing.JTextField();
        modelNameComBox = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("输入对话框");

        jLabel1.setText("请 输 入 表 别 名：");

        jLabel2.setText(org.openide.util.NbBundle.getMessage(TableAliasAndModelNameDlg.class, "TableAliasAndModelNameDlg.jLabel2.text")); // NOI18N

        tableAliasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableAliasTextFieldActionPerformed(evt);
            }
        });

        modelNameComBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        modelNameComBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modelNameComBoxItemStateChanged(evt);
            }
        });
        modelNameComBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNameComBoxActionPerformed(evt);
            }
        });

        okButton.setText(org.openide.util.NbBundle.getMessage(TableAliasAndModelNameDlg.class, "TableAliasAndModelNameDlg.okButton.text")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(org.openide.util.NbBundle.getMessage(TableAliasAndModelNameDlg.class, "TableAliasAndModelNameDlg.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(okButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addComponent(tableAliasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNameComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tableAliasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(modelNameComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableAliasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableAliasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAliasTextFieldActionPerformed

    private void modelNameComBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNameComBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNameComBoxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelAction();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        confirmAction();
    }//GEN-LAST:event_okButtonActionPerformed

    private void modelNameComBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modelNameComBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNameComBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableAliasAndModelNameDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableAliasAndModelNameDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableAliasAndModelNameDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableAliasAndModelNameDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TableAliasAndModelNameDlg dialog = new TableAliasAndModelNameDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox modelNameComBox;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField tableAliasTextField;
    // End of variables declaration//GEN-END:variables

    private void wfinit(String messageTxt, String tableAlias) {
        status = -1;
        int height = Toolkit.getDefaultToolkit().getScreenSize().height;
        int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        this.setLocation((int)(width/3.5), (int)(height/2.8));
        if(messageTxt != null){
            this.jLabel1.setText(messageTxt);
            info[0] = tableAlias;
        }
        if(tableAlias != null)
            this.tableAliasTextField.setText(tableAlias);
   //模型名称下拉列表框初始化
        String[] chartCategories = {"分页表格", "树状表格", "后端分页增删改查表格", "柱图", "饼图", "线型图", "散点图", "普通表格联动柱图", "雷达图", "仪表盘图"};
        this.modelNameComBox.removeAllItems();
        this.modelNameComBox.addItem("");
        for(int i=0; i < chartCategories.length; i++){
            this.modelNameComBox.addItem(chartCategories[i]);
        }
        this.modelNameComBox.setSelectedIndex(1);
        addWindowListener(new WindowAdapter(){
        //点击窗体右上角的×直接关闭窗体执行的方法
             @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        status = 1;
                        setVisible(false);
                    }
           });
        
        this.setModal(true);
        this.setVisible(true);
    }
    //获取窗体中输入的信息：表别名和模型名称
    public String[] getInfo(){
        if(status == 0){
            info[0] = this.tableAliasTextField.getText();
            info[1] = (String)this.modelNameComBox.getSelectedItem();
        }
        return info;
    }
//点击取消按钮触发的事件
    private void cancelAction() {
        status = 1;
        this.setVisible(false);
    }
//点击确认按钮触发的事件
    private void confirmAction() {
        status = 0;
        this.setVisible(false);
    }
//获取status值
    public int getStatus(){
        return status;
    }
}
