package com.bca.toolkit.top.tools.sql.impl.estyle;

import com.bca.pub.gui.jtablex.I_JTableDataHandler;
import com.bca.pub.gui.jtablex.I_TableRowGuiBinder;

/**
 * 编辑风格编码表管理：详细编辑form
 * @author 北京华夏翰科科技有限公司 http://www.hxhk.com.cn
 * 2012-10-02 23:06:11.656
 */
public class EditStyleCodeRowEditorForm extends javax.swing.JPanel implements I_TableRowGuiBinder<EditStyleCode> {

    /** Creates new form EditStyleCodeRowEditorForm */
    public EditStyleCodeRowEditorForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemCodeLabel = new javax.swing.JLabel();
        itemCodeField = new javax.swing.JTextField();
        compLabelLabel = new javax.swing.JLabel();
        compLabelField = new javax.swing.JTextField();
        sortNoLabel = new javax.swing.JLabel();
        sortNoField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setName("Form"); // NOI18N

        itemCodeLabel.setText("存储代码:");
        itemCodeLabel.setName("itemCodeLabel"); // NOI18N

        itemCodeField.setEditable(false);
        itemCodeField.setName("itemCodeField"); // NOI18N

        compLabelLabel.setText("控件标签:");
        compLabelLabel.setName("compLabelLabel"); // NOI18N

        compLabelField.setName("compLabelField"); // NOI18N

        sortNoLabel.setText("排序编号:");
        sortNoLabel.setName("sortNoLabel"); // NOI18N

        sortNoField.setName("sortNoField"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("取消");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(okButton)
                        .addGap(38, 38, 38)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemCodeLabel)
                                    .addComponent(compLabelLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(compLabelField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(itemCodeField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sortNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sortNoField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemCodeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compLabelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compLabelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sortNoLabel)
                            .addComponent(sortNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    if (h != null && bindingBean != null) {
        this.updateBean();
        this.h.fillRow(this.bindingRow, this.bindingBean);
    }
}//GEN-LAST:event_okButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.rebind(bindingRow, bindingBean);
}//GEN-LAST:event_cancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField compLabelField;
    private javax.swing.JLabel compLabelLabel;
    private javax.swing.JTextField itemCodeField;
    private javax.swing.JLabel itemCodeLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField sortNoField;
    private javax.swing.JLabel sortNoLabel;
    // End of variables declaration//GEN-END:variables
    int bindingRow = 0;
    EditStyleCode bindingBean = null;
    I_JTableDataHandler h;

    @Override
    public void rebind(int rowNo, EditStyleCode e) {
        this.bindingBean = e;
        this.bindingRow = rowNo;

        itemCodeField.setText(e==null || e.getItemCode()==null ? "" : e.getItemCode());
        compLabelField.setText(e==null || e.getCompLabel()==null ? "" : e.getCompLabel());
        sortNoField.setText(e==null ? "" : Integer.toString( e.getSortNo() ));

    }

    @Override
    public int getBindingRow() {
        return bindingRow;
    }

    @Override
    public EditStyleCode getBindingBean() {
        return bindingBean;
    }

    @Override
    public void setTableDataHandler(I_JTableDataHandler h) {
        this.h = h;
    }

    @Override
    public EditStyleCode updateBean() {
        // 从界面取对象....      
        if (bindingBean == null) {
            return null;
        }
        bindingBean.setItemCode(itemCodeField.getText());
        bindingBean.setCompLabel(compLabelField.getText());
        bindingBean.setSortNo(Integer.parseInt( sortNoField.getText() ));

        return this.bindingBean;
    }

    @Override
    public boolean isSaveEnable() {
        return true;
    }

    @Override
    public void setPkFieldsEditable(boolean b) {
        itemCodeField.setEditable(b);

    }
}
