/*
 * NTemplateForm.java
 *
 * Created on 2008年8月26日, 下午7:09
 */

package com.bca.toolkit.top;

import com.bca.pub.gui.BcaDockingForm;
import com.bca.pub.gui.BcaDockingUnit;
import net.infonode.docking.TabWindow;
import net.infonode.docking.View;

import com.bca.studio.templ.top.TResTopComponent;
import com.bca.studio.templ.top.TemplateWorkTopComponent;
import com.bca.studio.top.FixPalatteTopComponent;
/**
 *
 * @author  Administrator
 */
public class NTemplateForm extends BcaDockingForm {
    
    /** Creates new form BeanForm */
    public NTemplateForm() {
        //initComponents();
        setLayout(new java.awt.BorderLayout());

        super.doCreateDockWindows();
        createViews(); //create views
        super.showViews();
    }

//    private JComponent createViewComponentForDockingPanel(String text) {
//        StringBuffer sb = new StringBuffer();
//
//        for (int j = 0; j < 100; j++) {
//            sb.append(text + ".Docking Panel content -- Line " + j + "\n");
//        }
//        return new JScrollPane(new JTextArea(sb.toString()));
//    }

     //Create views  创建浮动窗口
    private void createViews() {
        BcaDockingUnit[] leftDockUnit = new BcaDockingUnit[1];
        BcaDockingUnit[] centerDockUnit = new BcaDockingUnit[1];

        leftDockUnit[0] = new BcaDockingUnit(TResTopComponent.getDefault(), 1f, null, "TRes窗口", super.getVIEW_ICON(), false);

        View[] rightViewPart = new View[2];
        rightViewPart[0] = new View("TemplateWork窗口", super.getVIEW_ICON(), TemplateWorkTopComponent.getDefault() );
        rightViewPart[1] = new View("小工具箱", super.getVIEW_ICON(), FixPalatteTopComponent.getDefault() );
        TabWindow rightPart = new TabWindow( rightViewPart );
        rightPart.setSelectedTab(0);
        View rightPartView = new View("Template", super.getVIEW_ICON(), rightPart);
        
        centerDockUnit[0] = new BcaDockingUnit(rightPartView, 1f, null, "右侧窗口", super.getVIEW_ICON(), false);

        super.setHorizontalLayout(0.3f, 0.7f, 0f);
        super.setVerticalLayout(1f, 0f);
        super.loadDockingForms(leftDockUnit, null, null, centerDockUnit);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.FlowLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify                     
    // End of variables declaration                   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
