package com.bca.toolkit.top.tools.sql.impl.estyle;

import com.bca.pub.gui.jtablex.JTableWorkPanel;
import com.bca.pub.tools.Wftool;

/**
 * 编辑风格编码表管理 列表清单 
 * @author 北京华夏翰科科技有限公司 http://www.hxhk.com.cn
 * 2012-10-02 23:06:11.656
 */
public class EditStyleCodeJTableForm extends javax.swing.JPanel {

    EditStyleCodeJTableModel tableModel = new EditStyleCodeJTableModel();
    JTableWorkPanel<EditStyleCode> tableWorkPanel = new JTableWorkPanel<EditStyleCode>(tableModel, !true, true);
    EditStyleCodeRowEditorForm ep; // = new EditStyleCodeRowEditorForm();  先不编辑详细行
    public EditStyleCodeJTableForm() {
        initComponents();
        wfinit();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        refreshButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        refreshButton.setText("刷新");
        refreshButton.setFocusable(false);
        refreshButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(refreshButton);

        upButton.setText("up");
        upButton.setFocusable(false);
        upButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        upButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(upButton);

        downButton.setText("down");
        downButton.setFocusable(false);
        downButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        downButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(downButton);

        newButton.setText("new");
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(newButton);

        deleteButton.setText("del");
        deleteButton.setFocusable(false);
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(deleteButton);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        tableModel.refreshAll();
        //totalField.setText(String.format(" 合计 %d 个呼叫 ", tableModel.getRowCount()));
    }//GEN-LAST:event_refreshButtonActionPerformed

private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
    tableWorkPanel.selectedRowsUp();
}//GEN-LAST:event_upButtonActionPerformed

private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
    tableWorkPanel.selectedRowsDown();
}//GEN-LAST:event_downButtonActionPerformed

private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
    tableWorkPanel.createNewRow();
}//GEN-LAST:event_newButtonActionPerformed

private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    tableWorkPanel.deleteSelectedRows();
}//GEN-LAST:event_deleteButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton downButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton newButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables

    private void wfinit() {
        tableWorkPanel.setMainLayoutType(JTableWorkPanel.LAYOUT_BY_BORDER, 0);
        this.add(this.tableWorkPanel, java.awt.BorderLayout.CENTER);
        Wftool.setToolButtonIcon(upButton, "up.gif", "上移", "");
        Wftool.setToolButtonIcon(downButton, "down.gif", "下移", "");
        Wftool.setToolButtonIcon(refreshButton, "refresh.gif", "刷新", "");
        Wftool.setToolButtonIcon(newButton, "new.gif", "新建", "");
        Wftool.setToolButtonIcon(deleteButton, "delete.gif", "删除", "");

        ep = new EditStyleCodeRowEditorForm();  // 编辑详细行
        ep.setTableDataHandler(tableModel);

        tableWorkPanel.addRowEditPanel("rowedit", ep, java.awt.BorderLayout.EAST);
    }
}
