/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FactoryUiSwitch_GuoXin.java
 *
 * Created on 2012-8-27, 10:28:15
 */
package com.bca.toolkit.top.tools.sql.impl.sh;

import com.bca.templ.pub.AbstractStudioApp;
import com.bca.toolkit.top.tools.sql.I_UiSwitch;
import com.bca.toolkit.top.tools.sql.SqlCreateModel;

/**
 *
 * @author pxz
 */
public class FactoryUiSwitch_ShouHen extends javax.swing.JDialog implements I_UiSwitch {

    SqlCreateModel sqlModel;

    /** Creates new form FactoryUiSwitch_GuoXin */
    public FactoryUiSwitch_ShouHen() {
        super(AbstractStudioApp.getMainFrameOnPossible(), true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        criteriaBox = new javax.swing.JCheckBox();
        listdevBox = new javax.swing.JCheckBox();
        addBox = new javax.swing.JCheckBox();
        expBox = new javax.swing.JCheckBox();
        impBox = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UI开关 -- 首亨框架");
        setName("Form"); // NOI18N

        jLabel1.setText("UI开关选项:");
        jLabel1.setName("jLabel1"); // NOI18N

        criteriaBox.setText("查询条件");
        criteriaBox.setName("criteriaBox"); // NOI18N

        listdevBox.setText("list");
        listdevBox.setName("listdevBox"); // NOI18N

        addBox.setText("input");
        addBox.setName("addBox"); // NOI18N

        expBox.setText("exp");
        expBox.setName("expBox"); // NOI18N

        impBox.setText("imp");
        impBox.setName("impBox"); // NOI18N

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("取消");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(criteriaBox)
                    .addComponent(listdevBox)
                    .addComponent(expBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(impBox)
                    .addComponent(addBox))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(criteriaBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBox)
                            .addComponent(listdevBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expBox)
                            .addComponent(impBox)
                            .addComponent(cancelButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(okButton)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    setMaskSwitch(criteriaBox.isSelected(), "criteria");
    setMaskSwitch(listdevBox.isSelected(), "jspList");
    setMaskSwitch(addBox.isSelected(), "jspInput");
//    setMaskSwitch(updateBox.isSelected(), "Info-update.jsp");
//    setMaskSwitch(viewBox.isSelected(), "Info-view.jsp");
    setMaskSwitch(expBox.isSelected(), "exp");
    setMaskSwitch(impBox.isSelected(), "imp");
//    setMaskSwitch(deleteBox.isSelected(), "delete");
    this.setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.setVisible(false);
}//GEN-LAST:event_cancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox criteriaBox;
    private javax.swing.JCheckBox expBox;
    private javax.swing.JCheckBox impBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox listdevBox;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void loadSwitches(SqlCreateModel sqlModel) {
        this.sqlModel = sqlModel;
        criteriaBox.setSelected(!sqlModel.isFieldMasked("ui", "criteria"));
        listdevBox.setSelected(!sqlModel.isFieldMasked("ui", "jspList"));
        addBox.setSelected(!sqlModel.isFieldMasked("ui", "jspInput"));
        //        updateBox.setSelected(!sqlModel.isFieldMasked("ui", "Info-update.jsp"));
        //        viewBox.setSelected(!sqlModel.isFieldMasked("ui", "Info-view.jsp"));
        expBox.setSelected(!sqlModel.isFieldMasked("ui", "exp"));
        impBox.setSelected(!sqlModel.isFieldMasked("ui", "imp"));
        //        deleteBox.setSelected(!sqlModel.isFieldMasked("ui", "delete"));
    }

    private void setMaskSwitch(boolean selected, String uiModuleName) {
        if (selected) {
            sqlModel.removeFieldMask("ui", uiModuleName);
        } else {
            sqlModel.maskField("ui", uiModuleName);
        }
    }

    @Override
    public boolean isReloadModelRequest() {
        return false;
    }
}
